desc: --pages-as-heap=yes
cmd: python ../../stime.py 3 ../../loop.exe
time_unit: i
#-----------
snapshot=0
#-----------
time=0
mem_heap_B=2465792
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=1
#-----------
time=797812
mem_heap_B=32153600
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=2
#-----------
time=2924582
mem_heap_B=32333824
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=3
#-----------
time=4239154
mem_heap_B=32600064
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=4
#-----------
time=4898870
mem_heap_B=32739328
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=5
#-----------
time=5976449
mem_heap_B=32735232
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=6
#-----------
time=7047244
mem_heap_B=32739328
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=7
#-----------
time=7819625
mem_heap_B=32735232
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=8
#-----------
time=8866413
mem_heap_B=32739328
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=9
#-----------
time=9571247
mem_heap_B=33157120
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=10
#-----------
time=10188757
mem_heap_B=33353728
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=11
#-----------
time=10924934
mem_heap_B=33357824
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=12
#-----------
time=11734418
mem_heap_B=33353728
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=13
#-----------
time=12464289
mem_heap_B=33357824
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=14
#-----------
time=13530432
mem_heap_B=33353728
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=detailed
n4: 33353728 (page allocation syscalls) mmap/mremap/brk, --alloc-fns, etc.
 n2: 26857472 0x4018429: mmap (syscall-template.S:82)
  n1: 26492928 0x4006B67: _dl_map_object_from_fd (dl-load.c:1283)
   n2: 26492928 0x4008698: _dl_map_object (dl-load.c:2568)
    n1: 24387584 0x400CFE0: openaux (dl-deps.c:65)
     n1: 24387584 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 24387584 0x400D6BC: _dl_map_object_deps (dl-deps.c:258)
       n1: 24387584 0x400350B: dl_main (rtld.c:1826)
        n1: 24387584 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 24387584 0x4005363: _dl_start (rtld.c:338)
          n1: 24387584 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 24387584 0x2: ???
            n1: 24387584 0x7FF0007A5: ???
             n1: 24387584 0x7FF0007AC: ???
              n1: 24387584 0x7FF0007BB: ???
               n0: 24387584 0x7FF0007BD: ???
    n1: 2105344 0x400188C: map_doit (rtld.c:633)
     n1: 2105344 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 2105344 0x4000ECD: do_preload (rtld.c:822)
       n1: 2105344 0x4004118: dl_main (rtld.c:1717)
        n1: 2105344 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 2105344 0x4005363: _dl_start (rtld.c:338)
          n1: 2105344 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 2105344 0x2: ???
            n1: 2105344 0x7FF0007A5: ???
             n1: 2105344 0x7FF0007AC: ???
              n1: 2105344 0x7FF0007BB: ???
               n0: 2105344 0x7FF0007BD: ???
  n0: 364544 in 4 places, all below massif's threshold (01.00%)
 n0: 3256320 0xFFFFFFFFFFFFFFFF: ???
 n3: 2637824 0x609A169: mmap (syscall-template.S:82)
  n1: 1609728 0x5FD7DC4: _nl_load_locale_from_archive (loadarchive.c:228)
   n1: 1609728 0x5FD6E11: _nl_find_locale (findlocale.c:107)
    n1: 1609728 0x5FD6678: setlocale (setlocale.c:303)
     n0: 1609728 0x41D2BA: main (in /usr/bin/python3.2mu)
  n1: 999424 0x602B5CB: _int_malloc (malloc.c:2400)
   n2: 999424 0x602D0B3: malloc (malloc.c:2924)
    n1: 798720 0x422657: PyObject_Malloc (in /usr/bin/python3.2mu)
     n0: 798720 in 3 places, all below massif's threshold (01.00%)
    n0: 200704 in 1 place, below massif's threshold (01.00%)
  n0: 28672 in 2 places, all below massif's threshold (01.00%)
 n1: 602112 0x60964D9: brk (brk.c:32)
  n1: 602112 0x6096583: sbrk (sbrk.c:54)
   n1: 602112 0x602F7D7: __default_morecore (morecore.c:49)
    n1: 602112 0x602B178: _int_malloc (malloc.c:2535)
     n1: 602112 0x602D0B3: malloc (malloc.c:2924)
      n0: 602112 in 4 places, all below massif's threshold (01.00%)
#-----------
snapshot=15
#-----------
time=14365333
mem_heap_B=33751040
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=16
#-----------
time=18543733
mem_heap_B=33755136
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=17
#-----------
time=19323477
mem_heap_B=33886208
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=18
#-----------
time=20461772
mem_heap_B=33890304
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=19
#-----------
time=21385137
mem_heap_B=33886208
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=20
#-----------
time=22296486
mem_heap_B=34156544
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=21
#-----------
time=23055936
mem_heap_B=34291712
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=22
#-----------
time=23594420
mem_heap_B=34295808
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=23
#-----------
time=24360804
mem_heap_B=34291712
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=24
#-----------
time=25199947
mem_heap_B=34295808
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=25
#-----------
time=25959609
mem_heap_B=34463744
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=26
#-----------
time=26770369
mem_heap_B=34729984
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=27
#-----------
time=27948337
mem_heap_B=34729984
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=detailed
n4: 34729984 (page allocation syscalls) mmap/mremap/brk, --alloc-fns, etc.
 n2: 26857472 0x4018429: mmap (syscall-template.S:82)
  n1: 26492928 0x4006B67: _dl_map_object_from_fd (dl-load.c:1283)
   n2: 26492928 0x4008698: _dl_map_object (dl-load.c:2568)
    n1: 24387584 0x400CFE0: openaux (dl-deps.c:65)
     n1: 24387584 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 24387584 0x400D6BC: _dl_map_object_deps (dl-deps.c:258)
       n1: 24387584 0x400350B: dl_main (rtld.c:1826)
        n1: 24387584 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 24387584 0x4005363: _dl_start (rtld.c:338)
          n1: 24387584 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 24387584 0x2: ???
            n1: 24387584 0x7FF0007A5: ???
             n1: 24387584 0x7FF0007AC: ???
              n1: 24387584 0x7FF0007BB: ???
               n0: 24387584 0x7FF0007BD: ???
    n1: 2105344 0x400188C: map_doit (rtld.c:633)
     n1: 2105344 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 2105344 0x4000ECD: do_preload (rtld.c:822)
       n1: 2105344 0x4004118: dl_main (rtld.c:1717)
        n1: 2105344 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 2105344 0x4005363: _dl_start (rtld.c:338)
          n1: 2105344 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 2105344 0x2: ???
            n1: 2105344 0x7FF0007A5: ???
             n1: 2105344 0x7FF0007AC: ???
              n1: 2105344 0x7FF0007BB: ???
               n0: 2105344 0x7FF0007BD: ???
  n0: 364544 in 4 places, all below massif's threshold (01.00%)
 n3: 3440640 0x609A169: mmap (syscall-template.S:82)
  n1: 1798144 0x602B5CB: _int_malloc (malloc.c:2400)
   n2: 1798144 0x602D0B3: malloc (malloc.c:2924)
    n2: 1597440 0x422657: PyObject_Malloc (in /usr/bin/python3.2mu)
     n0: 1064960 in 4 places, all below massif's threshold (01.00%)
     n1: 532480 0x4205CB: _PyObject_New (in /usr/bin/python3.2mu)
      n1: 532480 0x436B28: ??? (in /usr/bin/python3.2mu)
       n1: 532480 0x43A25B: ??? (in /usr/bin/python3.2mu)
        n1: 532480 0x47B1BB: ??? (in /usr/bin/python3.2mu)
         n0: 532480 in 2 places, all below massif's threshold (01.00%)
    n0: 200704 in 1 place, below massif's threshold (01.00%)
  n1: 1609728 0x5FD7DC4: _nl_load_locale_from_archive (loadarchive.c:228)
   n1: 1609728 0x5FD6E11: _nl_find_locale (findlocale.c:107)
    n1: 1609728 0x5FD6678: setlocale (setlocale.c:303)
     n0: 1609728 0x41D2BA: main (in /usr/bin/python3.2mu)
  n0: 32768 in 2 places, all below massif's threshold (01.00%)
 n0: 3256320 0xFFFFFFFFFFFFFFFF: ???
 n1: 1175552 0x60964D9: brk (brk.c:32)
  n1: 1175552 0x6096583: sbrk (sbrk.c:54)
   n1: 1175552 0x602F7D7: __default_morecore (morecore.c:49)
    n1: 1175552 0x602B178: _int_malloc (malloc.c:2535)
     n2: 1175552 0x602D0B3: malloc (malloc.c:2924)
      n0: 724992 in 4 places, all below massif's threshold (01.00%)
      n1: 450560 0x47CC5A: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python3.2mu)
       n1: 450560 0x4748EC: ??? (in /usr/bin/python3.2mu)
        n1: 450560 0x4772CF: ??? (in /usr/bin/python3.2mu)
         n1: 450560 0x477F7A: ??? (in /usr/bin/python3.2mu)
          n1: 450560 0x4781F5: ??? (in /usr/bin/python3.2mu)
           n1: 450560 0x4786D5: ??? (in /usr/bin/python3.2mu)
            n1: 450560 0x478F77: PyImport_ImportModuleLevel (in /usr/bin/python3.2mu)
             n1: 450560 0x4560F9: ??? (in /usr/bin/python3.2mu)
              n0: 450560 in 2 places, all below massif's threshold (01.00%)
#-----------
snapshot=28
#-----------
time=28948031
mem_heap_B=34725888
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=29
#-----------
time=30163266
mem_heap_B=34865152
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=detailed
n4: 34865152 (page allocation syscalls) mmap/mremap/brk, --alloc-fns, etc.
 n2: 26857472 0x4018429: mmap (syscall-template.S:82)
  n1: 26492928 0x4006B67: _dl_map_object_from_fd (dl-load.c:1283)
   n2: 26492928 0x4008698: _dl_map_object (dl-load.c:2568)
    n1: 24387584 0x400CFE0: openaux (dl-deps.c:65)
     n1: 24387584 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 24387584 0x400D6BC: _dl_map_object_deps (dl-deps.c:258)
       n1: 24387584 0x400350B: dl_main (rtld.c:1826)
        n1: 24387584 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 24387584 0x4005363: _dl_start (rtld.c:338)
          n1: 24387584 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 24387584 0x2: ???
            n1: 24387584 0x7FF0007A5: ???
             n1: 24387584 0x7FF0007AC: ???
              n1: 24387584 0x7FF0007BB: ???
               n0: 24387584 0x7FF0007BD: ???
    n1: 2105344 0x400188C: map_doit (rtld.c:633)
     n1: 2105344 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 2105344 0x4000ECD: do_preload (rtld.c:822)
       n1: 2105344 0x4004118: dl_main (rtld.c:1717)
        n1: 2105344 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 2105344 0x4005363: _dl_start (rtld.c:338)
          n1: 2105344 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 2105344 0x2: ???
            n1: 2105344 0x7FF0007A5: ???
             n1: 2105344 0x7FF0007AC: ???
              n1: 2105344 0x7FF0007BB: ???
               n0: 2105344 0x7FF0007BD: ???
  n0: 364544 in 4 places, all below massif's threshold (01.00%)
 n3: 3436544 0x609A169: mmap (syscall-template.S:82)
  n1: 1798144 0x602B5CB: _int_malloc (malloc.c:2400)
   n2: 1798144 0x602D0B3: malloc (malloc.c:2924)
    n2: 1597440 0x422657: PyObject_Malloc (in /usr/bin/python3.2mu)
     n0: 1064960 in 4 places, all below massif's threshold (01.00%)
     n1: 532480 0x4205CB: _PyObject_New (in /usr/bin/python3.2mu)
      n1: 532480 0x436B28: ??? (in /usr/bin/python3.2mu)
       n1: 532480 0x43A25B: ??? (in /usr/bin/python3.2mu)
        n1: 532480 0x47B1BB: ??? (in /usr/bin/python3.2mu)
         n0: 532480 in 2 places, all below massif's threshold (01.00%)
    n0: 200704 in 1 place, below massif's threshold (01.00%)
  n1: 1609728 0x5FD7DC4: _nl_load_locale_from_archive (loadarchive.c:228)
   n1: 1609728 0x5FD6E11: _nl_find_locale (findlocale.c:107)
    n1: 1609728 0x5FD6678: setlocale (setlocale.c:303)
     n0: 1609728 0x41D2BA: main (in /usr/bin/python3.2mu)
  n0: 28672 in 2 places, all below massif's threshold (01.00%)
 n0: 3256320 0xFFFFFFFFFFFFFFFF: ???
 n1: 1314816 0x60964D9: brk (brk.c:32)
  n1: 1314816 0x6096583: sbrk (sbrk.c:54)
   n1: 1314816 0x602F7D7: __default_morecore (morecore.c:49)
    n1: 1314816 0x602B178: _int_malloc (malloc.c:2535)
     n2: 1314816 0x602D0B3: malloc (malloc.c:2924)
      n0: 724992 in 4 places, all below massif's threshold (01.00%)
      n1: 589824 0x47CC5A: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python3.2mu)
       n1: 589824 0x4748EC: ??? (in /usr/bin/python3.2mu)
        n1: 589824 0x4772CF: ??? (in /usr/bin/python3.2mu)
         n1: 589824 0x477F7A: ??? (in /usr/bin/python3.2mu)
          n1: 589824 0x4781F5: ??? (in /usr/bin/python3.2mu)
           n1: 589824 0x4786D5: ??? (in /usr/bin/python3.2mu)
            n1: 589824 0x478F77: PyImport_ImportModuleLevel (in /usr/bin/python3.2mu)
             n2: 589824 0x4560F9: ??? (in /usr/bin/python3.2mu)
              n1: 438272 0x41ED75: PyObject_Call (in /usr/bin/python3.2mu)
               n1: 438272 0x457914: PyEval_CallObjectWithKeywords (in /usr/bin/python3.2mu)
                n1: 438272 0x45A2F4: PyEval_EvalFrameEx (in /usr/bin/python3.2mu)
                 n1: 438272 0x45FFD6: PyEval_EvalCodeEx (in /usr/bin/python3.2mu)
                  n1: 438272 0x460B49: PyEval_EvalCode (in /usr/bin/python3.2mu)
                   n1: 438272 0x4770EE: PyImport_ExecCodeModuleWithPathnames (in /usr/bin/python3.2mu)
                    n1: 438272 0x477343: ??? (in /usr/bin/python3.2mu)
                     n1: 438272 0x477F7A: ??? (in /usr/bin/python3.2mu)
                      n1: 438272 0x4781F5: ??? (in /usr/bin/python3.2mu)
                       n1: 438272 0x4786D5: ??? (in /usr/bin/python3.2mu)
                        n1: 438272 0x478F77: PyImport_ImportModuleLevel (in /usr/bin/python3.2mu)
                         n1: 438272 0x4560F9: ??? (in /usr/bin/python3.2mu)
                          n1: 438272 0x41ED75: PyObject_Call (in /usr/bin/python3.2mu)
                           n1: 438272 0x457914: PyEval_CallObjectWithKeywords (in /usr/bin/python3.2mu)
                            n1: 438272 0x45A2F4: PyEval_EvalFrameEx (in /usr/bin/python3.2mu)
                             n1: 438272 0x45FFD6: PyEval_EvalCodeEx (in /usr/bin/python3.2mu)
                              n0: 438272 0x460B49: PyEval_EvalCode (in /usr/bin/python3.2mu)
              n0: 151552 in 1 place, below massif's threshold (01.00%)
#-----------
snapshot=30
#-----------
time=31052929
mem_heap_B=34865152
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=31
#-----------
time=32273768
mem_heap_B=35131392
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=32
#-----------
time=32277255
mem_heap_B=35168256
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=33
#-----------
time=35902155
mem_heap_B=35172352
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=34
#-----------
time=37124343
mem_heap_B=35303424
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=35
#-----------
time=81578456
mem_heap_B=35307520
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=36
#-----------
time=82328427
mem_heap_B=35303424
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=37
#-----------
time=86314849
mem_heap_B=35307520
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=38
#-----------
time=87218804
mem_heap_B=35770368
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=39
#-----------
time=88243862
mem_heap_B=35766272
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=40
#-----------
time=90977162
mem_heap_B=35913728
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=41
#-----------
time=91436042
mem_heap_B=36200448
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=42
#-----------
time=112008241
mem_heap_B=36380672
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=43
#-----------
time=112710810
mem_heap_B=36384768
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=detailed
n4: 36384768 (page allocation syscalls) mmap/mremap/brk, --alloc-fns, etc.
 n2: 26857472 0x4018429: mmap (syscall-template.S:82)
  n1: 26492928 0x4006B67: _dl_map_object_from_fd (dl-load.c:1283)
   n2: 26492928 0x4008698: _dl_map_object (dl-load.c:2568)
    n1: 24387584 0x400CFE0: openaux (dl-deps.c:65)
     n1: 24387584 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 24387584 0x400D6BC: _dl_map_object_deps (dl-deps.c:258)
       n1: 24387584 0x400350B: dl_main (rtld.c:1826)
        n1: 24387584 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 24387584 0x4005363: _dl_start (rtld.c:338)
          n1: 24387584 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 24387584 0x2: ???
            n1: 24387584 0x7FF0007A5: ???
             n1: 24387584 0x7FF0007AC: ???
              n1: 24387584 0x7FF0007BB: ???
               n0: 24387584 0x7FF0007BD: ???
    n1: 2105344 0x400188C: map_doit (rtld.c:633)
     n1: 2105344 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 2105344 0x4000ECD: do_preload (rtld.c:822)
       n1: 2105344 0x4004118: dl_main (rtld.c:1717)
        n1: 2105344 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 2105344 0x4005363: _dl_start (rtld.c:338)
          n1: 2105344 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 2105344 0x2: ???
            n1: 2105344 0x7FF0007A5: ???
             n1: 2105344 0x7FF0007AC: ???
              n1: 2105344 0x7FF0007BB: ???
               n0: 2105344 0x7FF0007BD: ???
  n0: 364544 in 4 places, all below massif's threshold (01.00%)
 n3: 3440640 0x609A169: mmap (syscall-template.S:82)
  n1: 1798144 0x602B5CB: _int_malloc (malloc.c:2400)
   n2: 1798144 0x602D0B3: malloc (malloc.c:2924)
    n2: 1597440 0x422657: PyObject_Malloc (in /usr/bin/python3.2mu)
     n0: 1064960 in 4 places, all below massif's threshold (01.00%)
     n1: 532480 0x4205CB: _PyObject_New (in /usr/bin/python3.2mu)
      n1: 532480 0x436B28: ??? (in /usr/bin/python3.2mu)
       n1: 532480 0x43A25B: ??? (in /usr/bin/python3.2mu)
        n1: 532480 0x47B1BB: ??? (in /usr/bin/python3.2mu)
         n0: 532480 in 2 places, all below massif's threshold (01.00%)
    n0: 200704 in 1 place, below massif's threshold (01.00%)
  n1: 1609728 0x5FD7DC4: _nl_load_locale_from_archive (loadarchive.c:228)
   n1: 1609728 0x5FD6E11: _nl_find_locale (findlocale.c:107)
    n1: 1609728 0x5FD6678: setlocale (setlocale.c:303)
     n0: 1609728 0x41D2BA: main (in /usr/bin/python3.2mu)
  n0: 32768 in 2 places, all below massif's threshold (01.00%)
 n0: 3256320 0xFFFFFFFFFFFFFFFF: ???
 n1: 2830336 0x60964D9: brk (brk.c:32)
  n1: 2830336 0x6096583: sbrk (sbrk.c:54)
   n1: 2830336 0x602F7D7: __default_morecore (morecore.c:49)
    n1: 2830336 0x602B178: _int_malloc (malloc.c:2535)
     n4: 2830336 0x602D0B3: malloc (malloc.c:2924)
      n2: 892928 0x422657: PyObject_Malloc (in /usr/bin/python3.2mu)
       n1: 589824 0x4205CB: _PyObject_New (in /usr/bin/python3.2mu)
        n1: 589824 0x436B28: ??? (in /usr/bin/python3.2mu)
         n0: 589824 in 2 places, all below massif's threshold (01.00%)
       n0: 303104 in 1 place, below massif's threshold (01.00%)
      n1: 749568 0x47CC5A: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python3.2mu)
       n1: 749568 0x4748EC: ??? (in /usr/bin/python3.2mu)
        n1: 749568 0x4772CF: ??? (in /usr/bin/python3.2mu)
         n1: 749568 0x477F7A: ??? (in /usr/bin/python3.2mu)
          n1: 749568 0x4781F5: ??? (in /usr/bin/python3.2mu)
           n1: 749568 0x4786D5: ??? (in /usr/bin/python3.2mu)
            n1: 749568 0x478F77: PyImport_ImportModuleLevel (in /usr/bin/python3.2mu)
             n2: 749568 0x4560F9: ??? (in /usr/bin/python3.2mu)
              n1: 438272 0x41ED75: PyObject_Call (in /usr/bin/python3.2mu)
               n1: 438272 0x457914: PyEval_CallObjectWithKeywords (in /usr/bin/python3.2mu)
                n1: 438272 0x45A2F4: PyEval_EvalFrameEx (in /usr/bin/python3.2mu)
                 n1: 438272 0x45FFD6: PyEval_EvalCodeEx (in /usr/bin/python3.2mu)
                  n1: 438272 0x460B49: PyEval_EvalCode (in /usr/bin/python3.2mu)
                   n1: 438272 0x4770EE: PyImport_ExecCodeModuleWithPathnames (in /usr/bin/python3.2mu)
                    n1: 438272 0x477343: ??? (in /usr/bin/python3.2mu)
                     n1: 438272 0x477F7A: ??? (in /usr/bin/python3.2mu)
                      n1: 438272 0x4781F5: ??? (in /usr/bin/python3.2mu)
                       n1: 438272 0x4786D5: ??? (in /usr/bin/python3.2mu)
                        n1: 438272 0x478F77: PyImport_ImportModuleLevel (in /usr/bin/python3.2mu)
                         n1: 438272 0x4560F9: ??? (in /usr/bin/python3.2mu)
                          n1: 438272 0x41ED75: PyObject_Call (in /usr/bin/python3.2mu)
                           n1: 438272 0x457914: PyEval_CallObjectWithKeywords (in /usr/bin/python3.2mu)
                            n1: 438272 0x45A2F4: PyEval_EvalFrameEx (in /usr/bin/python3.2mu)
                             n1: 438272 0x45FFD6: PyEval_EvalCodeEx (in /usr/bin/python3.2mu)
                              n0: 438272 0x460B49: PyEval_EvalCode (in /usr/bin/python3.2mu)
              n0: 311296 in 1 place, below massif's threshold (01.00%)
      n0: 692224 in 5 places, all below massif's threshold (01.00%)
      n1: 495616 0x536EAE: ??? (in /usr/bin/python3.2mu)
       n0: 495616 in 3 places, all below massif's threshold (01.00%)
#-----------
snapshot=44
#-----------
time=113754105
mem_heap_B=51232768
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=45
#-----------
time=114483829
mem_heap_B=59936768
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=46
#-----------
time=115011084
mem_heap_B=85397504
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=47
#-----------
time=117172725
mem_heap_B=219615232
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=48
#-----------
time=117172740
mem_heap_B=168816640
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=peak
n4: 168816640 (page allocation syscalls) mmap/mremap/brk, --alloc-fns, etc.
 n4: 112369664 0x609A169: mmap (syscall-template.S:82)
  n1: 83419136 0x6028377: new_heap (arena.c:554)
   n1: 83419136 0x60292B3: arena_get2.isra.5.part.6 (arena.c:712)
    n1: 83419136 0x602D1E7: malloc (arena.c:824)
     n1: 83419136 0x47FC32: ??? (in /usr/bin/python3.2mu)
      n1: 83419136 0x480835: PyGILState_Ensure (in /usr/bin/python3.2mu)
       n1: 83419136 0x64E41A9: SandboxPolicy_entry (in /usr/local/lib/python3.2/dist-packages/sandbox/_sandbox.cpython-32mu.so)
        n1: 83419136 0x66EEE5E: sandbox_watcher (in /usr/lib/libsandbox.so.0.3.5)
         n0: 83419136 0x4C2EE98: start_thread (pthread_create.c:308)
  n3: 25178112 0x4C2FA2C: pthread_create@@GLIBC_2.2.5 (allocatestack.c:495)
   n1: 8392704 0x400F304: call_init.part.0 (dl-init.c:85)
    n1: 8392704 0x400F3DD: _dl_init (dl-init.c:52)
     n1: 8392704 0x4013AD8: dl_open_worker (dl-open.c:549)
      n1: 8392704 0x400F174: _dl_catch_error (dl-error.c:178)
       n1: 8392704 0x4013318: _dl_open (dl-open.c:639)
        n1: 8392704 0x4E44F24: dlopen_doit (dlopen.c:67)
         n1: 8392704 0x400F174: _dl_catch_error (dl-error.c:178)
          n1: 8392704 0x4E4552D: _dlerror_run (dlerror.c:164)
           n1: 8392704 0x4E44FBF: dlopen@@GLIBC_2.2.5 (dlopen.c:88)
            n1: 8392704 0x4925C8: _PyImport_GetDynLoadFunc (in /usr/bin/python3.2mu)
             n1: 8392704 0x479A14: _PyImport_LoadDynamicModule (in /usr/bin/python3.2mu)
              n1: 8392704 0x477F7A: ??? (in /usr/bin/python3.2mu)
               n1: 8392704 0x47851C: ??? (in /usr/bin/python3.2mu)
                n1: 8392704 0x478798: ??? (in /usr/bin/python3.2mu)
                 n1: 8392704 0x478F77: PyImport_ImportModuleLevel (in /usr/bin/python3.2mu)
                  n1: 8392704 0x4560F9: ??? (in /usr/bin/python3.2mu)
                   n1: 8392704 0x41ED75: PyObject_Call (in /usr/bin/python3.2mu)
                    n1: 8392704 0x457914: PyEval_CallObjectWithKeywords (in /usr/bin/python3.2mu)
                     n1: 8392704 0x45A2F4: PyEval_EvalFrameEx (in /usr/bin/python3.2mu)
                      n1: 8392704 0x45FFD6: PyEval_EvalCodeEx (in /usr/bin/python3.2mu)
                       n1: 8392704 0x460B49: PyEval_EvalCode (in /usr/bin/python3.2mu)
                        n1: 8392704 0x4770EE: PyImport_ExecCodeModuleWithPathnames (in /usr/bin/python3.2mu)
                         n1: 8392704 0x477343: ??? (in /usr/bin/python3.2mu)
                          n1: 8392704 0x478DCA: ??? (in /usr/bin/python3.2mu)
                           n1: 8392704 0x477F7A: ??? (in /usr/bin/python3.2mu)
                            n1: 8392704 0x4781F5: ??? (in /usr/bin/python3.2mu)
                             n1: 8392704 0x4786D5: ??? (in /usr/bin/python3.2mu)
                              n0: 8392704 0x478F77: PyImport_ImportModuleLevel (in /usr/bin/python3.2mu)
   n1: 8392704 0x66F12FD: sandbox_execute (in /usr/lib/libsandbox.so.0.3.5)
    n1: 8392704 0x64E2F7C: Sandbox_run (in /usr/local/lib/python3.2/dist-packages/sandbox/_sandbox.cpython-32mu.so)
     n1: 8392704 0x45C3CA: PyEval_EvalFrameEx (in /usr/bin/python3.2mu)
      n1: 8392704 0x460483: PyEval_EvalCodeEx (in /usr/bin/python3.2mu)
       n1: 8392704 0x45C3A5: PyEval_EvalFrameEx (in /usr/bin/python3.2mu)
        n1: 8392704 0x45FFD6: PyEval_EvalCodeEx (in /usr/bin/python3.2mu)
         n1: 8392704 0x460B49: PyEval_EvalCode (in /usr/bin/python3.2mu)
          n1: 8392704 0x480C93: ??? (in /usr/bin/python3.2mu)
           n1: 8392704 0x48273F: PyRun_FileExFlags (in /usr/bin/python3.2mu)
            n1: 8392704 0x4831A7: PyRun_SimpleFileExFlags (in /usr/bin/python3.2mu)
             n1: 8392704 0x494001: Py_Main (in /usr/bin/python3.2mu)
              n0: 8392704 0x41D305: main (in /usr/bin/python3.2mu)
   n1: 8392704 0x66F1322: sandbox_execute (in /usr/lib/libsandbox.so.0.3.5)
    n1: 8392704 0x64E2F7C: Sandbox_run (in /usr/local/lib/python3.2/dist-packages/sandbox/_sandbox.cpython-32mu.so)
     n1: 8392704 0x45C3CA: PyEval_EvalFrameEx (in /usr/bin/python3.2mu)
      n1: 8392704 0x460483: PyEval_EvalCodeEx (in /usr/bin/python3.2mu)
       n1: 8392704 0x45C3A5: PyEval_EvalFrameEx (in /usr/bin/python3.2mu)
        n1: 8392704 0x45FFD6: PyEval_EvalCodeEx (in /usr/bin/python3.2mu)
         n1: 8392704 0x460B49: PyEval_EvalCode (in /usr/bin/python3.2mu)
          n1: 8392704 0x480C93: ??? (in /usr/bin/python3.2mu)
           n1: 8392704 0x48273F: PyRun_FileExFlags (in /usr/bin/python3.2mu)
            n1: 8392704 0x4831A7: PyRun_SimpleFileExFlags (in /usr/bin/python3.2mu)
             n1: 8392704 0x494001: Py_Main (in /usr/bin/python3.2mu)
              n0: 8392704 0x41D305: main (in /usr/bin/python3.2mu)
  n1: 2134016 0x602B5CB: _int_malloc (malloc.c:2400)
   n1: 2134016 0x602D0B3: malloc (malloc.c:2924)
    n0: 2134016 in 3 places, all below massif's threshold (01.00%)
  n0: 1638400 in 4 places, all below massif's threshold (01.00%)
 n3: 50360320 0x4018429: mmap (syscall-template.S:82)
  n1: 45731840 0x4006B67: _dl_map_object_from_fd (dl-load.c:1283)
   n3: 45731840 0x4008698: _dl_map_object (dl-load.c:2568)
    n1: 37203968 0x400CFE0: openaux (dl-deps.c:65)
     n1: 37203968 0x400F174: _dl_catch_error (dl-error.c:178)
      n2: 37203968 0x400D6BC: _dl_map_object_deps (dl-deps.c:258)
       n1: 24387584 0x400350B: dl_main (rtld.c:1826)
        n1: 24387584 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 24387584 0x4005363: _dl_start (rtld.c:338)
          n1: 24387584 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 24387584 0x2: ???
            n1: 24387584 0x7FF0007A5: ???
             n1: 24387584 0x7FF0007AC: ???
              n1: 24387584 0x7FF0007BB: ???
               n0: 24387584 0x7FF0007BD: ???
       n1: 12816384 0x40138A7: dl_open_worker (dl-open.c:262)
        n1: 12816384 0x400F174: _dl_catch_error (dl-error.c:178)
         n2: 12816384 0x4013318: _dl_open (dl-open.c:639)
          n1: 8462336 0x4E44F24: dlopen_doit (dlopen.c:67)
           n1: 8462336 0x400F174: _dl_catch_error (dl-error.c:178)
            n1: 8462336 0x4E4552D: _dlerror_run (dlerror.c:164)
             n1: 8462336 0x4E44FBF: dlopen@@GLIBC_2.2.5 (dlopen.c:88)
              n1: 8462336 0x4925C8: _PyImport_GetDynLoadFunc (in /usr/bin/python3.2mu)
               n1: 8462336 0x479A14: _PyImport_LoadDynamicModule (in /usr/bin/python3.2mu)
                n1: 8462336 0x477F7A: ??? (in /usr/bin/python3.2mu)
                 n1: 8462336 0x47851C: ??? (in /usr/bin/python3.2mu)
                  n1: 8462336 0x478798: ??? (in /usr/bin/python3.2mu)
                   n1: 8462336 0x478F77: PyImport_ImportModuleLevel (in /usr/bin/python3.2mu)
                    n1: 8462336 0x4560F9: ??? (in /usr/bin/python3.2mu)
                     n1: 8462336 0x41ED75: PyObject_Call (in /usr/bin/python3.2mu)
                      n1: 8462336 0x457914: PyEval_CallObjectWithKeywords (in /usr/bin/python3.2mu)
                       n1: 8462336 0x45A2F4: PyEval_EvalFrameEx (in /usr/bin/python3.2mu)
                        n1: 8462336 0x45FFD6: PyEval_EvalCodeEx (in /usr/bin/python3.2mu)
                         n1: 8462336 0x460B49: PyEval_EvalCode (in /usr/bin/python3.2mu)
                          n1: 8462336 0x4770EE: PyImport_ExecCodeModuleWithPathnames (in /usr/bin/python3.2mu)
                           n1: 8462336 0x477343: ??? (in /usr/bin/python3.2mu)
                            n1: 8462336 0x478DCA: ??? (in /usr/bin/python3.2mu)
                             n1: 8462336 0x477F7A: ??? (in /usr/bin/python3.2mu)
                              n0: 8462336 0x4781F5: ??? (in /usr/bin/python3.2mu)
          n1: 4354048 0x60DA700: do_dlopen (dl-libc.c:89)
           n1: 4354048 0x400F174: _dl_catch_error (dl-error.c:178)
            n1: 4354048 0x60DA7C2: __libc_dlopen_mode (dl-libc.c:48)
             n1: 4354048 0x60AFB1C: nss_load_library.isra.1 (nsswitch.c:372)
              n2: 4354048 0x60B057B: __nss_lookup_function (nsswitch.c:474)
               n1: 2203648 0x60B078A: __nss_lookup (nsswitch.c:202)
                n1: 2203648 0x6068E16: getpwuid_r@@GLIBC_2.2.5 (getXXbyYY_r.c:203)
                 n1: 2203648 0x60685F1: getpwuid (getXXbyYY.c:117)
                  n1: 2203648 0x66F0D6F: sandbox_check (in /usr/lib/libsandbox.so.0.3.5)
                   n1: 2203648 0x64E3FAE: Sandbox_new (in /usr/local/lib/python3.2/dist-packages/sandbox/_sandbox.cpython-32mu.so)
                    n1: 2203648 0x42DBA3: ??? (in /usr/bin/python3.2mu)
                     n1: 2203648 0x41ED75: PyObject_Call (in /usr/bin/python3.2mu)
                      n1: 2203648 0x45C254: PyEval_EvalFrameEx (in /usr/bin/python3.2mu)
                       n1: 2203648 0x45FFD6: PyEval_EvalCodeEx (in /usr/bin/python3.2mu)
                        n1: 2203648 0x460B49: PyEval_EvalCode (in /usr/bin/python3.2mu)
                         n1: 2203648 0x480C93: ??? (in /usr/bin/python3.2mu)
                          n1: 2203648 0x48273F: PyRun_FileExFlags (in /usr/bin/python3.2mu)
                           n1: 2203648 0x4831A7: PyRun_SimpleFileExFlags (in /usr/bin/python3.2mu)
                            n1: 2203648 0x494001: Py_Main (in /usr/bin/python3.2mu)
                             n0: 2203648 0x41D305: main (in /usr/bin/python3.2mu)
               n1: 2150400 0x775363D: ???
                n1: 2150400 0x6068CFB: getpwuid_r@@GLIBC_2.2.5 (getXXbyYY_r.c:256)
                 n1: 2150400 0x60685F1: getpwuid (getXXbyYY.c:117)
                  n1: 2150400 0x66F0D6F: sandbox_check (in /usr/lib/libsandbox.so.0.3.5)
                   n1: 2150400 0x64E3FAE: Sandbox_new (in /usr/local/lib/python3.2/dist-packages/sandbox/_sandbox.cpython-32mu.so)
                    n1: 2150400 0x42DBA3: ??? (in /usr/bin/python3.2mu)
                     n1: 2150400 0x41ED75: PyObject_Call (in /usr/bin/python3.2mu)
                      n1: 2150400 0x45C254: PyEval_EvalFrameEx (in /usr/bin/python3.2mu)
                       n1: 2150400 0x45FFD6: PyEval_EvalCodeEx (in /usr/bin/python3.2mu)
                        n1: 2150400 0x460B49: PyEval_EvalCode (in /usr/bin/python3.2mu)
                         n1: 2150400 0x480C93: ??? (in /usr/bin/python3.2mu)
                          n1: 2150400 0x48273F: PyRun_FileExFlags (in /usr/bin/python3.2mu)
                           n1: 2150400 0x4831A7: PyRun_SimpleFileExFlags (in /usr/bin/python3.2mu)
                            n1: 2150400 0x494001: Py_Main (in /usr/bin/python3.2mu)
                             n0: 2150400 0x41D305: main (in /usr/bin/python3.2mu)
    n1: 6422528 0x4013849: dl_open_worker (dl-open.c:225)
     n1: 6422528 0x400F174: _dl_catch_error (dl-error.c:178)
      n2: 6422528 0x4013318: _dl_open (dl-open.c:639)
       n1: 4280320 0x60DA700: do_dlopen (dl-libc.c:89)
        n1: 4280320 0x400F174: _dl_catch_error (dl-error.c:178)
         n1: 4280320 0x60DA7C2: __libc_dlopen_mode (dl-libc.c:48)
          n1: 4280320 0x60AFB1C: nss_load_library.isra.1 (nsswitch.c:372)
           n2: 4280320 0x60B057B: __nss_lookup_function (nsswitch.c:474)
            n1: 2146304 0x775363D: ???
             n1: 2146304 0x6068CFB: getpwuid_r@@GLIBC_2.2.5 (getXXbyYY_r.c:256)
              n1: 2146304 0x60685F1: getpwuid (getXXbyYY.c:117)
               n1: 2146304 0x66F0D6F: sandbox_check (in /usr/lib/libsandbox.so.0.3.5)
                n1: 2146304 0x64E3FAE: Sandbox_new (in /usr/local/lib/python3.2/dist-packages/sandbox/_sandbox.cpython-32mu.so)
                 n1: 2146304 0x42DBA3: ??? (in /usr/bin/python3.2mu)
                  n1: 2146304 0x41ED75: PyObject_Call (in /usr/bin/python3.2mu)
                   n1: 2146304 0x45C254: PyEval_EvalFrameEx (in /usr/bin/python3.2mu)
                    n1: 2146304 0x45FFD6: PyEval_EvalCodeEx (in /usr/bin/python3.2mu)
                     n1: 2146304 0x460B49: PyEval_EvalCode (in /usr/bin/python3.2mu)
                      n1: 2146304 0x480C93: ??? (in /usr/bin/python3.2mu)
                       n1: 2146304 0x48273F: PyRun_FileExFlags (in /usr/bin/python3.2mu)
                        n1: 2146304 0x4831A7: PyRun_SimpleFileExFlags (in /usr/bin/python3.2mu)
                         n1: 2146304 0x494001: Py_Main (in /usr/bin/python3.2mu)
                          n0: 2146304 0x41D305: main (in /usr/bin/python3.2mu)
            n1: 2134016 0x60B078A: __nss_lookup (nsswitch.c:202)
             n1: 2134016 0x6068E16: getpwuid_r@@GLIBC_2.2.5 (getXXbyYY_r.c:203)
              n1: 2134016 0x60685F1: getpwuid (getXXbyYY.c:117)
               n1: 2134016 0x66F0D6F: sandbox_check (in /usr/lib/libsandbox.so.0.3.5)
                n1: 2134016 0x64E3FAE: Sandbox_new (in /usr/local/lib/python3.2/dist-packages/sandbox/_sandbox.cpython-32mu.so)
                 n1: 2134016 0x42DBA3: ??? (in /usr/bin/python3.2mu)
                  n1: 2134016 0x41ED75: PyObject_Call (in /usr/bin/python3.2mu)
                   n1: 2134016 0x45C254: PyEval_EvalFrameEx (in /usr/bin/python3.2mu)
                    n1: 2134016 0x45FFD6: PyEval_EvalCodeEx (in /usr/bin/python3.2mu)
                     n1: 2134016 0x460B49: PyEval_EvalCode (in /usr/bin/python3.2mu)
                      n1: 2134016 0x480C93: ??? (in /usr/bin/python3.2mu)
                       n1: 2134016 0x48273F: PyRun_FileExFlags (in /usr/bin/python3.2mu)
                        n1: 2134016 0x4831A7: PyRun_SimpleFileExFlags (in /usr/bin/python3.2mu)
                         n1: 2134016 0x494001: Py_Main (in /usr/bin/python3.2mu)
                          n0: 2134016 0x41D305: main (in /usr/bin/python3.2mu)
       n1: 2142208 0x4E44F24: dlopen_doit (dlopen.c:67)
        n1: 2142208 0x400F174: _dl_catch_error (dl-error.c:178)
         n1: 2142208 0x4E4552D: _dlerror_run (dlerror.c:164)
          n1: 2142208 0x4E44FBF: dlopen@@GLIBC_2.2.5 (dlopen.c:88)
           n1: 2142208 0x4925C8: _PyImport_GetDynLoadFunc (in /usr/bin/python3.2mu)
            n1: 2142208 0x479A14: _PyImport_LoadDynamicModule (in /usr/bin/python3.2mu)
             n1: 2142208 0x477F7A: ??? (in /usr/bin/python3.2mu)
              n1: 2142208 0x47851C: ??? (in /usr/bin/python3.2mu)
               n1: 2142208 0x478798: ??? (in /usr/bin/python3.2mu)
                n1: 2142208 0x478F77: PyImport_ImportModuleLevel (in /usr/bin/python3.2mu)
                 n1: 2142208 0x4560F9: ??? (in /usr/bin/python3.2mu)
                  n1: 2142208 0x41ED75: PyObject_Call (in /usr/bin/python3.2mu)
                   n1: 2142208 0x457914: PyEval_CallObjectWithKeywords (in /usr/bin/python3.2mu)
                    n1: 2142208 0x45A2F4: PyEval_EvalFrameEx (in /usr/bin/python3.2mu)
                     n1: 2142208 0x45FFD6: PyEval_EvalCodeEx (in /usr/bin/python3.2mu)
                      n1: 2142208 0x460B49: PyEval_EvalCode (in /usr/bin/python3.2mu)
                       n1: 2142208 0x4770EE: PyImport_ExecCodeModuleWithPathnames (in /usr/bin/python3.2mu)
                        n1: 2142208 0x477343: ??? (in /usr/bin/python3.2mu)
                         n1: 2142208 0x478DCA: ??? (in /usr/bin/python3.2mu)
                          n1: 2142208 0x477F7A: ??? (in /usr/bin/python3.2mu)
                           n1: 2142208 0x4781F5: ??? (in /usr/bin/python3.2mu)
                            n1: 2142208 0x4786D5: ??? (in /usr/bin/python3.2mu)
                             n1: 2142208 0x478F77: PyImport_ImportModuleLevel (in /usr/bin/python3.2mu)
                              n0: 2142208 0x4560F9: ??? (in /usr/bin/python3.2mu)
    n1: 2105344 0x400188C: map_doit (rtld.c:633)
     n1: 2105344 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 2105344 0x4000ECD: do_preload (rtld.c:822)
       n1: 2105344 0x4004118: dl_main (rtld.c:1717)
        n1: 2105344 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 2105344 0x4005363: _dl_start (rtld.c:338)
          n1: 2105344 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 2105344 0x2: ???
            n1: 2105344 0x7FF0007A5: ???
             n1: 2105344 0x7FF0007AC: ???
              n1: 2105344 0x7FF0007BB: ???
               n0: 2105344 0x7FF0007BD: ???
  n1: 4259840 0x4007148: _dl_map_object_from_fd (dl-load.c:1392)
   n1: 4259840 0x4008698: _dl_map_object (dl-load.c:2568)
    n1: 4259840 0x400CFE0: openaux (dl-deps.c:65)
     n1: 4259840 0x400F174: _dl_catch_error (dl-error.c:178)
      n2: 4259840 0x400D6BC: _dl_map_object_deps (dl-deps.c:258)
       n1: 4202496 0x40138A7: dl_open_worker (dl-open.c:262)
        n1: 4202496 0x400F174: _dl_catch_error (dl-error.c:178)
         n2: 4202496 0x4013318: _dl_open (dl-open.c:639)
          n1: 4194304 0x4E44F24: dlopen_doit (dlopen.c:67)
           n1: 4194304 0x400F174: _dl_catch_error (dl-error.c:178)
            n1: 4194304 0x4E4552D: _dlerror_run (dlerror.c:164)
             n1: 4194304 0x4E44FBF: dlopen@@GLIBC_2.2.5 (dlopen.c:88)
              n1: 4194304 0x4925C8: _PyImport_GetDynLoadFunc (in /usr/bin/python3.2mu)
               n1: 4194304 0x479A14: _PyImport_LoadDynamicModule (in /usr/bin/python3.2mu)
                n1: 4194304 0x477F7A: ??? (in /usr/bin/python3.2mu)
                 n1: 4194304 0x47851C: ??? (in /usr/bin/python3.2mu)
                  n1: 4194304 0x478798: ??? (in /usr/bin/python3.2mu)
                   n1: 4194304 0x478F77: PyImport_ImportModuleLevel (in /usr/bin/python3.2mu)
                    n1: 4194304 0x4560F9: ??? (in /usr/bin/python3.2mu)
                     n1: 4194304 0x41ED75: PyObject_Call (in /usr/bin/python3.2mu)
                      n1: 4194304 0x457914: PyEval_CallObjectWithKeywords (in /usr/bin/python3.2mu)
                       n1: 4194304 0x45A2F4: PyEval_EvalFrameEx (in /usr/bin/python3.2mu)
                        n1: 4194304 0x45FFD6: PyEval_EvalCodeEx (in /usr/bin/python3.2mu)
                         n1: 4194304 0x460B49: PyEval_EvalCode (in /usr/bin/python3.2mu)
                          n1: 4194304 0x4770EE: PyImport_ExecCodeModuleWithPathnames (in /usr/bin/python3.2mu)
                           n1: 4194304 0x477343: ??? (in /usr/bin/python3.2mu)
                            n1: 4194304 0x478DCA: ??? (in /usr/bin/python3.2mu)
                             n1: 4194304 0x477F7A: ??? (in /usr/bin/python3.2mu)
                              n0: 4194304 0x4781F5: ??? (in /usr/bin/python3.2mu)
          n0: 8192 in 1 place, below massif's threshold (01.00%)
       n0: 57344 in 1 place, below massif's threshold (01.00%)
  n0: 368640 in 3 places, all below massif's threshold (01.00%)
 n0: 3256320 0xFFFFFFFFFFFFFFFF: ???
 n1: 2830336 0x60964D9: brk (brk.c:32)
  n1: 2830336 0x6096583: sbrk (sbrk.c:54)
   n1: 2830336 0x602F7D7: __default_morecore (morecore.c:49)
    n1: 2830336 0x602B178: _int_malloc (malloc.c:2535)
     n1: 2830336 0x602D0B3: malloc (malloc.c:2924)
      n0: 2830336 in 8 places, all below massif's threshold (01.00%)
#-----------
snapshot=49
#-----------
time=117172740
mem_heap_B=168812544
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=50
#-----------
time=119172143
mem_heap_B=152170496
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=51
#-----------
time=121265730
mem_heap_B=150560768
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=52
#-----------
time=121265788
mem_heap_B=150532096
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=53
#-----------
time=121270775
mem_heap_B=142139392
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=54
#-----------
time=121271237
mem_heap_B=133746688
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=55
#-----------
time=121271717
mem_heap_B=125353984
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=56
#-----------
time=121277794
mem_heap_B=123219968
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=57
#-----------
time=121281553
mem_heap_B=121073664
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=58
#-----------
time=121282177
mem_heap_B=118870016
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=detailed
n4: 118870016 (page allocation syscalls) mmap/mremap/brk, --alloc-fns, etc.
 n3: 68907008 0x609A169: mmap (syscall-template.S:82)
  n1: 67108864 0x6028377: new_heap (arena.c:554)
   n1: 67108864 0x60292B3: arena_get2.isra.5.part.6 (arena.c:712)
    n1: 67108864 0x602D1E7: malloc (arena.c:824)
     n1: 67108864 0x47FC32: ??? (in /usr/bin/python3.2mu)
      n1: 67108864 0x480835: PyGILState_Ensure (in /usr/bin/python3.2mu)
       n1: 67108864 0x64E41A9: SandboxPolicy_entry (in /usr/local/lib/python3.2/dist-packages/sandbox/_sandbox.cpython-32mu.so)
        n1: 67108864 0x66EEE5E: sandbox_watcher (in /usr/lib/libsandbox.so.0.3.5)
         n0: 67108864 0x4C2EE98: start_thread (pthread_create.c:308)
  n1: 1798144 0x602B5CB: _int_malloc (malloc.c:2400)
   n2: 1798144 0x602D0B3: malloc (malloc.c:2924)
    n1: 1597440 0x422657: PyObject_Malloc (in /usr/bin/python3.2mu)
     n0: 1597440 in 5 places, all below massif's threshold (01.00%)
    n0: 200704 in 2 places, all below massif's threshold (01.00%)
  n0: 0 in 5 places, all below massif's threshold (01.00%)
 n3: 43876352 0x4018429: mmap (syscall-template.S:82)
  n1: 39280640 0x4006B67: _dl_map_object_from_fd (dl-load.c:1283)
   n3: 39280640 0x4008698: _dl_map_object (dl-load.c:2568)
    n1: 35016704 0x400CFE0: openaux (dl-deps.c:65)
     n1: 35016704 0x400F174: _dl_catch_error (dl-error.c:178)
      n2: 35016704 0x400D6BC: _dl_map_object_deps (dl-deps.c:258)
       n1: 24387584 0x400350B: dl_main (rtld.c:1826)
        n1: 24387584 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 24387584 0x4005363: _dl_start (rtld.c:338)
          n1: 24387584 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 24387584 0x2: ???
            n1: 24387584 0x7FF0007A5: ???
             n1: 24387584 0x7FF0007AC: ???
              n1: 24387584 0x7FF0007BB: ???
               n0: 24387584 0x7FF0007BD: ???
       n1: 10629120 0x40138A7: dl_open_worker (dl-open.c:262)
        n1: 10629120 0x400F174: _dl_catch_error (dl-error.c:178)
         n2: 10629120 0x4013318: _dl_open (dl-open.c:639)
          n1: 8462336 0x4E44F24: dlopen_doit (dlopen.c:67)
           n1: 8462336 0x400F174: _dl_catch_error (dl-error.c:178)
            n1: 8462336 0x4E4552D: _dlerror_run (dlerror.c:164)
             n1: 8462336 0x4E44FBF: dlopen@@GLIBC_2.2.5 (dlopen.c:88)
              n1: 8462336 0x4925C8: _PyImport_GetDynLoadFunc (in /usr/bin/python3.2mu)
               n1: 8462336 0x479A14: _PyImport_LoadDynamicModule (in /usr/bin/python3.2mu)
                n1: 8462336 0x477F7A: ??? (in /usr/bin/python3.2mu)
                 n1: 8462336 0x47851C: ??? (in /usr/bin/python3.2mu)
                  n1: 8462336 0x478798: ??? (in /usr/bin/python3.2mu)
                   n1: 8462336 0x478F77: PyImport_ImportModuleLevel (in /usr/bin/python3.2mu)
                    n1: 8462336 0x4560F9: ??? (in /usr/bin/python3.2mu)
                     n1: 8462336 0x41ED75: PyObject_Call (in /usr/bin/python3.2mu)
                      n1: 8462336 0x457914: PyEval_CallObjectWithKeywords (in /usr/bin/python3.2mu)
                       n1: 8462336 0x45A2F4: PyEval_EvalFrameEx (in /usr/bin/python3.2mu)
                        n1: 8462336 0x45FFD6: PyEval_EvalCodeEx (in /usr/bin/python3.2mu)
                         n1: 8462336 0x460B49: PyEval_EvalCode (in /usr/bin/python3.2mu)
                          n1: 8462336 0x4770EE: PyImport_ExecCodeModuleWithPathnames (in /usr/bin/python3.2mu)
                           n1: 8462336 0x477343: ??? (in /usr/bin/python3.2mu)
                            n1: 8462336 0x478DCA: ??? (in /usr/bin/python3.2mu)
                             n1: 8462336 0x477F7A: ??? (in /usr/bin/python3.2mu)
                              n0: 8462336 0x4781F5: ??? (in /usr/bin/python3.2mu)
          n1: 2166784 0x60DA700: do_dlopen (dl-libc.c:89)
           n1: 2166784 0x400F174: _dl_catch_error (dl-error.c:178)
            n1: 2166784 0x60DA7C2: __libc_dlopen_mode (dl-libc.c:48)
             n1: 2166784 0x60AFB1C: nss_load_library.isra.1 (nsswitch.c:372)
              n2: 2166784 0x60B057B: __nss_lookup_function (nsswitch.c:474)
               n1: 2150400 0x775363D: ???
                n1: 2150400 0x6068CFB: getpwuid_r@@GLIBC_2.2.5 (getXXbyYY_r.c:256)
                 n1: 2150400 0x60685F1: getpwuid (getXXbyYY.c:117)
                  n1: 2150400 0x66F0D6F: sandbox_check (in /usr/lib/libsandbox.so.0.3.5)
                   n1: 2150400 0x64E3FAE: Sandbox_new (in /usr/local/lib/python3.2/dist-packages/sandbox/_sandbox.cpython-32mu.so)
                    n1: 2150400 0x42DBA3: ??? (in /usr/bin/python3.2mu)
                     n1: 2150400 0x41ED75: PyObject_Call (in /usr/bin/python3.2mu)
                      n1: 2150400 0x45C254: PyEval_EvalFrameEx (in /usr/bin/python3.2mu)
                       n1: 2150400 0x45FFD6: PyEval_EvalCodeEx (in /usr/bin/python3.2mu)
                        n1: 2150400 0x460B49: PyEval_EvalCode (in /usr/bin/python3.2mu)
                         n1: 2150400 0x480C93: ??? (in /usr/bin/python3.2mu)
                          n1: 2150400 0x48273F: PyRun_FileExFlags (in /usr/bin/python3.2mu)
                           n1: 2150400 0x4831A7: PyRun_SimpleFileExFlags (in /usr/bin/python3.2mu)
                            n1: 2150400 0x494001: Py_Main (in /usr/bin/python3.2mu)
                             n0: 2150400 0x41D305: main (in /usr/bin/python3.2mu)
               n0: 16384 in 1 place, below massif's threshold (01.00%)
    n1: 2158592 0x4013849: dl_open_worker (dl-open.c:225)
     n1: 2158592 0x400F174: _dl_catch_error (dl-error.c:178)
      n2: 2158592 0x4013318: _dl_open (dl-open.c:639)
       n1: 2142208 0x4E44F24: dlopen_doit (dlopen.c:67)
        n1: 2142208 0x400F174: _dl_catch_error (dl-error.c:178)
         n1: 2142208 0x4E4552D: _dlerror_run (dlerror.c:164)
          n1: 2142208 0x4E44FBF: dlopen@@GLIBC_2.2.5 (dlopen.c:88)
           n1: 2142208 0x4925C8: _PyImport_GetDynLoadFunc (in /usr/bin/python3.2mu)
            n1: 2142208 0x479A14: _PyImport_LoadDynamicModule (in /usr/bin/python3.2mu)
             n1: 2142208 0x477F7A: ??? (in /usr/bin/python3.2mu)
              n1: 2142208 0x47851C: ??? (in /usr/bin/python3.2mu)
               n1: 2142208 0x478798: ??? (in /usr/bin/python3.2mu)
                n1: 2142208 0x478F77: PyImport_ImportModuleLevel (in /usr/bin/python3.2mu)
                 n1: 2142208 0x4560F9: ??? (in /usr/bin/python3.2mu)
                  n1: 2142208 0x41ED75: PyObject_Call (in /usr/bin/python3.2mu)
                   n1: 2142208 0x457914: PyEval_CallObjectWithKeywords (in /usr/bin/python3.2mu)
                    n1: 2142208 0x45A2F4: PyEval_EvalFrameEx (in /usr/bin/python3.2mu)
                     n1: 2142208 0x45FFD6: PyEval_EvalCodeEx (in /usr/bin/python3.2mu)
                      n1: 2142208 0x460B49: PyEval_EvalCode (in /usr/bin/python3.2mu)
                       n1: 2142208 0x4770EE: PyImport_ExecCodeModuleWithPathnames (in /usr/bin/python3.2mu)
                        n1: 2142208 0x477343: ??? (in /usr/bin/python3.2mu)
                         n1: 2142208 0x478DCA: ??? (in /usr/bin/python3.2mu)
                          n1: 2142208 0x477F7A: ??? (in /usr/bin/python3.2mu)
                           n1: 2142208 0x4781F5: ??? (in /usr/bin/python3.2mu)
                            n1: 2142208 0x4786D5: ??? (in /usr/bin/python3.2mu)
                             n1: 2142208 0x478F77: PyImport_ImportModuleLevel (in /usr/bin/python3.2mu)
                              n0: 2142208 0x4560F9: ??? (in /usr/bin/python3.2mu)
       n0: 16384 in 1 place, below massif's threshold (01.00%)
    n1: 2105344 0x400188C: map_doit (rtld.c:633)
     n1: 2105344 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 2105344 0x4000ECD: do_preload (rtld.c:822)
       n1: 2105344 0x4004118: dl_main (rtld.c:1717)
        n1: 2105344 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 2105344 0x4005363: _dl_start (rtld.c:338)
          n1: 2105344 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 2105344 0x2: ???
            n1: 2105344 0x7FF0007A5: ???
             n1: 2105344 0x7FF0007AC: ???
              n1: 2105344 0x7FF0007BB: ???
               n0: 2105344 0x7FF0007BD: ???
  n1: 4251648 0x4007148: _dl_map_object_from_fd (dl-load.c:1392)
   n1: 4251648 0x4008698: _dl_map_object (dl-load.c:2568)
    n1: 4251648 0x400CFE0: openaux (dl-deps.c:65)
     n1: 4251648 0x400F174: _dl_catch_error (dl-error.c:178)
      n2: 4251648 0x400D6BC: _dl_map_object_deps (dl-deps.c:258)
       n1: 4194304 0x40138A7: dl_open_worker (dl-open.c:262)
        n1: 4194304 0x400F174: _dl_catch_error (dl-error.c:178)
         n2: 4194304 0x4013318: _dl_open (dl-open.c:639)
          n1: 4194304 0x4E44F24: dlopen_doit (dlopen.c:67)
           n1: 4194304 0x400F174: _dl_catch_error (dl-error.c:178)
            n1: 4194304 0x4E4552D: _dlerror_run (dlerror.c:164)
             n1: 4194304 0x4E44FBF: dlopen@@GLIBC_2.2.5 (dlopen.c:88)
              n1: 4194304 0x4925C8: _PyImport_GetDynLoadFunc (in /usr/bin/python3.2mu)
               n1: 4194304 0x479A14: _PyImport_LoadDynamicModule (in /usr/bin/python3.2mu)
                n1: 4194304 0x477F7A: ??? (in /usr/bin/python3.2mu)
                 n1: 4194304 0x47851C: ??? (in /usr/bin/python3.2mu)
                  n1: 4194304 0x478798: ??? (in /usr/bin/python3.2mu)
                   n1: 4194304 0x478F77: PyImport_ImportModuleLevel (in /usr/bin/python3.2mu)
                    n1: 4194304 0x4560F9: ??? (in /usr/bin/python3.2mu)
                     n1: 4194304 0x41ED75: PyObject_Call (in /usr/bin/python3.2mu)
                      n1: 4194304 0x457914: PyEval_CallObjectWithKeywords (in /usr/bin/python3.2mu)
                       n1: 4194304 0x45A2F4: PyEval_EvalFrameEx (in /usr/bin/python3.2mu)
                        n1: 4194304 0x45FFD6: PyEval_EvalCodeEx (in /usr/bin/python3.2mu)
                         n1: 4194304 0x460B49: PyEval_EvalCode (in /usr/bin/python3.2mu)
                          n1: 4194304 0x4770EE: PyImport_ExecCodeModuleWithPathnames (in /usr/bin/python3.2mu)
                           n1: 4194304 0x477343: ??? (in /usr/bin/python3.2mu)
                            n1: 4194304 0x478DCA: ??? (in /usr/bin/python3.2mu)
                             n1: 4194304 0x477F7A: ??? (in /usr/bin/python3.2mu)
                              n0: 4194304 0x4781F5: ??? (in /usr/bin/python3.2mu)
          n0: 0 in 1 place, below massif's threshold (01.00%)
       n0: 57344 in 1 place, below massif's threshold (01.00%)
  n0: 344064 in 3 places, all below massif's threshold (01.00%)
 n0: 3256320 0xFFFFFFFFFFFFFFFF: ???
 n1: 2830336 0x60964D9: brk (brk.c:32)
  n1: 2830336 0x6096583: sbrk (sbrk.c:54)
   n1: 2830336 0x602F7D7: __default_morecore (morecore.c:49)
    n1: 2830336 0x602B178: _int_malloc (malloc.c:2535)
     n1: 2830336 0x602D0B3: malloc (malloc.c:2924)
      n0: 2830336 in 8 places, all below massif's threshold (01.00%)
#-----------
snapshot=59
#-----------
time=121282903
mem_heap_B=116719616
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
