desc: --pages-as-heap=yes
cmd: python ../../stime.py 3 ../../hello.exe
time_unit: i
#-----------
snapshot=0
#-----------
time=0
mem_heap_B=2560000
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=1
#-----------
time=100279
mem_heap_B=30035968
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=2
#-----------
time=551015
mem_heap_B=30015488
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=detailed
n2: 30015488 (page allocation syscalls) mmap/mremap/brk, --alloc-fns, etc.
 n2: 26775552 0x4018429: mmap (syscall-template.S:82)
  n1: 26411008 0x4006B67: _dl_map_object_from_fd (dl-load.c:1283)
   n2: 26411008 0x4008698: _dl_map_object (dl-load.c:2568)
    n1: 24305664 0x400CFE0: openaux (dl-deps.c:65)
     n1: 24305664 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 24305664 0x400D6BC: _dl_map_object_deps (dl-deps.c:258)
       n1: 24305664 0x400350B: dl_main (rtld.c:1826)
        n1: 24305664 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 24305664 0x4005363: _dl_start (rtld.c:338)
          n1: 24305664 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 24305664 0x2: ???
            n1: 24305664 0x7FF0007A5: ???
             n1: 24305664 0x7FF0007AC: ???
              n1: 24305664 0x7FF0007BB: ???
               n0: 24305664 0x7FF0007BD: ???
    n1: 2105344 0x400188C: map_doit (rtld.c:633)
     n1: 2105344 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 2105344 0x4000ECD: do_preload (rtld.c:822)
       n1: 2105344 0x4004118: dl_main (rtld.c:1717)
        n1: 2105344 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 2105344 0x4005363: _dl_start (rtld.c:338)
          n1: 2105344 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 2105344 0x2: ???
            n1: 2105344 0x7FF0007A5: ???
             n1: 2105344 0x7FF0007AC: ???
              n1: 2105344 0x7FF0007BB: ???
               n0: 2105344 0x7FF0007BD: ???
  n0: 364544 in 4 places, all below massif's threshold (01.00%)
 n0: 3239936 0xFFFFFFFFFFFFFFFF: ???
#-----------
snapshot=3
#-----------
time=638123
mem_heap_B=30146560
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=4
#-----------
time=708918
mem_heap_B=30412800
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=5
#-----------
time=2691919
mem_heap_B=30593024
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=6
#-----------
time=3657528
mem_heap_B=30859264
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=7
#-----------
time=3939063
mem_heap_B=30863360
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=8
#-----------
time=4230887
mem_heap_B=30863360
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=detailed
n4: 30863360 (page allocation syscalls) mmap/mremap/brk, --alloc-fns, etc.
 n2: 26771456 0x4018429: mmap (syscall-template.S:82)
  n1: 26411008 0x4006B67: _dl_map_object_from_fd (dl-load.c:1283)
   n2: 26411008 0x4008698: _dl_map_object (dl-load.c:2568)
    n1: 24305664 0x400CFE0: openaux (dl-deps.c:65)
     n1: 24305664 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 24305664 0x400D6BC: _dl_map_object_deps (dl-deps.c:258)
       n1: 24305664 0x400350B: dl_main (rtld.c:1826)
        n1: 24305664 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 24305664 0x4005363: _dl_start (rtld.c:338)
          n1: 24305664 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 24305664 0x2: ???
            n1: 24305664 0x7FF0007A5: ???
             n1: 24305664 0x7FF0007AC: ???
              n1: 24305664 0x7FF0007BB: ???
               n0: 24305664 0x7FF0007BD: ???
    n1: 2105344 0x400188C: map_doit (rtld.c:633)
     n1: 2105344 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 2105344 0x4000ECD: do_preload (rtld.c:822)
       n1: 2105344 0x4004118: dl_main (rtld.c:1717)
        n1: 2105344 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 2105344 0x4005363: _dl_start (rtld.c:338)
          n1: 2105344 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 2105344 0x2: ???
            n1: 2105344 0x7FF0007A5: ???
             n1: 2105344 0x7FF0007AC: ???
              n1: 2105344 0x7FF0007BB: ???
               n0: 2105344 0x7FF0007BD: ???
  n0: 360448 in 4 places, all below massif's threshold (01.00%)
 n0: 3239936 0xFFFFFFFFFFFFFFFF: ???
 n2: 536576 0x5E70169: mmap (syscall-template.S:82)
  n1: 532480 0x5E015CB: _int_malloc (malloc.c:2400)
   n1: 532480 0x5E030B3: malloc (malloc.c:2924)
    n1: 532480 0x423FC6: PyObject_Malloc (in /usr/bin/python2.7)
     n1: 532480 0x54390B: _PyObject_GC_Malloc (in /usr/bin/python2.7)
      n1: 532480 0x4DFB30: PyTuple_New (in /usr/bin/python2.7)
       n0: 532480 in 2 places, all below massif's threshold (01.00%)
  n0: 4096 in 1 place, below massif's threshold (01.00%)
 n1: 315392 0x5E6C4D9: brk (brk.c:32)
  n1: 315392 0x5E6C583: sbrk (sbrk.c:54)
   n1: 315392 0x5E057D7: __default_morecore (morecore.c:49)
    n1: 315392 0x5E01178: _int_malloc (malloc.c:2535)
     n1: 315392 0x5E030B3: malloc (malloc.c:2924)
      n0: 315392 in 2 places, all below massif's threshold (01.00%)
#-----------
snapshot=9
#-----------
time=4250983
mem_heap_B=30863360
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=10
#-----------
time=4819519
mem_heap_B=30859264
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=11
#-----------
time=4892333
mem_heap_B=30998528
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=12
#-----------
time=5526423
mem_heap_B=31002624
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=13
#-----------
time=5725201
mem_heap_B=30998528
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=14
#-----------
time=5821834
mem_heap_B=30998528
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=15
#-----------
time=5901928
mem_heap_B=31203328
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=detailed
n4: 31203328 (page allocation syscalls) mmap/mremap/brk, --alloc-fns, etc.
 n2: 26771456 0x4018429: mmap (syscall-template.S:82)
  n1: 26411008 0x4006B67: _dl_map_object_from_fd (dl-load.c:1283)
   n2: 26411008 0x4008698: _dl_map_object (dl-load.c:2568)
    n1: 24305664 0x400CFE0: openaux (dl-deps.c:65)
     n1: 24305664 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 24305664 0x400D6BC: _dl_map_object_deps (dl-deps.c:258)
       n1: 24305664 0x400350B: dl_main (rtld.c:1826)
        n1: 24305664 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 24305664 0x4005363: _dl_start (rtld.c:338)
          n1: 24305664 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 24305664 0x2: ???
            n1: 24305664 0x7FF0007A5: ???
             n1: 24305664 0x7FF0007AC: ???
              n1: 24305664 0x7FF0007BB: ???
               n0: 24305664 0x7FF0007BD: ???
    n1: 2105344 0x400188C: map_doit (rtld.c:633)
     n1: 2105344 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 2105344 0x4000ECD: do_preload (rtld.c:822)
       n1: 2105344 0x4004118: dl_main (rtld.c:1717)
        n1: 2105344 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 2105344 0x4005363: _dl_start (rtld.c:338)
          n1: 2105344 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 2105344 0x2: ???
            n1: 2105344 0x7FF0007A5: ???
             n1: 2105344 0x7FF0007AC: ???
              n1: 2105344 0x7FF0007BB: ???
               n0: 2105344 0x7FF0007BD: ???
  n0: 360448 in 4 places, all below massif's threshold (01.00%)
 n0: 3239936 0xFFFFFFFFFFFFFFFF: ???
 n2: 737280 0x5E70169: mmap (syscall-template.S:82)
  n1: 733184 0x5E015CB: _int_malloc (malloc.c:2400)
   n2: 733184 0x5E030B3: malloc (malloc.c:2924)
    n1: 532480 0x423FC6: PyObject_Malloc (in /usr/bin/python2.7)
     n1: 532480 0x54390B: _PyObject_GC_Malloc (in /usr/bin/python2.7)
      n1: 532480 0x4DFB30: PyTuple_New (in /usr/bin/python2.7)
       n0: 532480 in 2 places, all below massif's threshold (01.00%)
    n0: 200704 in 1 place, below massif's threshold (01.00%)
  n0: 4096 in 1 place, below massif's threshold (01.00%)
 n1: 454656 0x5E6C4D9: brk (brk.c:32)
  n1: 454656 0x5E6C583: sbrk (sbrk.c:54)
   n1: 454656 0x5E057D7: __default_morecore (morecore.c:49)
    n1: 454656 0x5E01178: _int_malloc (malloc.c:2535)
     n2: 454656 0x5E030B3: malloc (malloc.c:2924)
      n1: 319488 0x4F8EBD: ??? (in /usr/bin/python2.7)
       n0: 319488 in 2 places, all below massif's threshold (01.00%)
      n0: 135168 in 1 place, below massif's threshold (01.00%)
#-----------
snapshot=16
#-----------
time=5988137
mem_heap_B=31203328
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=detailed
n4: 31203328 (page allocation syscalls) mmap/mremap/brk, --alloc-fns, etc.
 n2: 26771456 0x4018429: mmap (syscall-template.S:82)
  n1: 26411008 0x4006B67: _dl_map_object_from_fd (dl-load.c:1283)
   n2: 26411008 0x4008698: _dl_map_object (dl-load.c:2568)
    n1: 24305664 0x400CFE0: openaux (dl-deps.c:65)
     n1: 24305664 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 24305664 0x400D6BC: _dl_map_object_deps (dl-deps.c:258)
       n1: 24305664 0x400350B: dl_main (rtld.c:1826)
        n1: 24305664 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 24305664 0x4005363: _dl_start (rtld.c:338)
          n1: 24305664 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 24305664 0x2: ???
            n1: 24305664 0x7FF0007A5: ???
             n1: 24305664 0x7FF0007AC: ???
              n1: 24305664 0x7FF0007BB: ???
               n0: 24305664 0x7FF0007BD: ???
    n1: 2105344 0x400188C: map_doit (rtld.c:633)
     n1: 2105344 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 2105344 0x4000ECD: do_preload (rtld.c:822)
       n1: 2105344 0x4004118: dl_main (rtld.c:1717)
        n1: 2105344 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 2105344 0x4005363: _dl_start (rtld.c:338)
          n1: 2105344 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 2105344 0x2: ???
            n1: 2105344 0x7FF0007A5: ???
             n1: 2105344 0x7FF0007AC: ???
              n1: 2105344 0x7FF0007BB: ???
               n0: 2105344 0x7FF0007BD: ???
  n0: 360448 in 4 places, all below massif's threshold (01.00%)
 n0: 3239936 0xFFFFFFFFFFFFFFFF: ???
 n2: 737280 0x5E70169: mmap (syscall-template.S:82)
  n1: 733184 0x5E015CB: _int_malloc (malloc.c:2400)
   n2: 733184 0x5E030B3: malloc (malloc.c:2924)
    n1: 532480 0x423FC6: PyObject_Malloc (in /usr/bin/python2.7)
     n1: 532480 0x54390B: _PyObject_GC_Malloc (in /usr/bin/python2.7)
      n1: 532480 0x4DFB30: PyTuple_New (in /usr/bin/python2.7)
       n0: 532480 in 2 places, all below massif's threshold (01.00%)
    n0: 200704 in 1 place, below massif's threshold (01.00%)
  n0: 4096 in 1 place, below massif's threshold (01.00%)
 n1: 454656 0x5E6C4D9: brk (brk.c:32)
  n1: 454656 0x5E6C583: sbrk (sbrk.c:54)
   n1: 454656 0x5E057D7: __default_morecore (morecore.c:49)
    n1: 454656 0x5E01178: _int_malloc (malloc.c:2535)
     n2: 454656 0x5E030B3: malloc (malloc.c:2924)
      n1: 319488 0x4F8EBD: ??? (in /usr/bin/python2.7)
       n0: 319488 in 2 places, all below massif's threshold (01.00%)
      n0: 135168 in 1 place, below massif's threshold (01.00%)
#-----------
snapshot=17
#-----------
time=6016039
mem_heap_B=31203328
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=18
#-----------
time=6237079
mem_heap_B=31199232
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=19
#-----------
time=6311701
mem_heap_B=31199232
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=20
#-----------
time=6411070
mem_heap_B=31199232
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=21
#-----------
time=7037882
mem_heap_B=31203328
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=22
#-----------
time=7527954
mem_heap_B=31199232
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=23
#-----------
time=7570611
mem_heap_B=31203328
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=detailed
n4: 31203328 (page allocation syscalls) mmap/mremap/brk, --alloc-fns, etc.
 n2: 26771456 0x4018429: mmap (syscall-template.S:82)
  n1: 26411008 0x4006B67: _dl_map_object_from_fd (dl-load.c:1283)
   n2: 26411008 0x4008698: _dl_map_object (dl-load.c:2568)
    n1: 24305664 0x400CFE0: openaux (dl-deps.c:65)
     n1: 24305664 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 24305664 0x400D6BC: _dl_map_object_deps (dl-deps.c:258)
       n1: 24305664 0x400350B: dl_main (rtld.c:1826)
        n1: 24305664 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 24305664 0x4005363: _dl_start (rtld.c:338)
          n1: 24305664 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 24305664 0x2: ???
            n1: 24305664 0x7FF0007A5: ???
             n1: 24305664 0x7FF0007AC: ???
              n1: 24305664 0x7FF0007BB: ???
               n0: 24305664 0x7FF0007BD: ???
    n1: 2105344 0x400188C: map_doit (rtld.c:633)
     n1: 2105344 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 2105344 0x4000ECD: do_preload (rtld.c:822)
       n1: 2105344 0x4004118: dl_main (rtld.c:1717)
        n1: 2105344 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 2105344 0x4005363: _dl_start (rtld.c:338)
          n1: 2105344 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 2105344 0x2: ???
            n1: 2105344 0x7FF0007A5: ???
             n1: 2105344 0x7FF0007AC: ???
              n1: 2105344 0x7FF0007BB: ???
               n0: 2105344 0x7FF0007BD: ???
  n0: 360448 in 4 places, all below massif's threshold (01.00%)
 n0: 3239936 0xFFFFFFFFFFFFFFFF: ???
 n2: 737280 0x5E70169: mmap (syscall-template.S:82)
  n1: 733184 0x5E015CB: _int_malloc (malloc.c:2400)
   n2: 733184 0x5E030B3: malloc (malloc.c:2924)
    n1: 532480 0x423FC6: PyObject_Malloc (in /usr/bin/python2.7)
     n1: 532480 0x54390B: _PyObject_GC_Malloc (in /usr/bin/python2.7)
      n1: 532480 0x4DFB30: PyTuple_New (in /usr/bin/python2.7)
       n0: 532480 in 2 places, all below massif's threshold (01.00%)
    n0: 200704 in 1 place, below massif's threshold (01.00%)
  n0: 4096 in 1 place, below massif's threshold (01.00%)
 n1: 454656 0x5E6C4D9: brk (brk.c:32)
  n1: 454656 0x5E6C583: sbrk (sbrk.c:54)
   n1: 454656 0x5E057D7: __default_morecore (morecore.c:49)
    n1: 454656 0x5E01178: _int_malloc (malloc.c:2535)
     n2: 454656 0x5E030B3: malloc (malloc.c:2924)
      n1: 319488 0x4F8EBD: ??? (in /usr/bin/python2.7)
       n0: 319488 in 2 places, all below massif's threshold (01.00%)
      n0: 135168 in 1 place, below massif's threshold (01.00%)
#-----------
snapshot=24
#-----------
time=7780761
mem_heap_B=31469568
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=25
#-----------
time=7979197
mem_heap_B=31465472
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=26
#-----------
time=7994212
mem_heap_B=31469568
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=27
#-----------
time=8084348
mem_heap_B=31465472
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=28
#-----------
time=8102984
mem_heap_B=31469568
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=29
#-----------
time=8313852
mem_heap_B=31465472
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=30
#-----------
time=10130024
mem_heap_B=31600640
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=31
#-----------
time=11391429
mem_heap_B=31604736
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=32
#-----------
time=11481733
mem_heap_B=31600640
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=33
#-----------
time=11747766
mem_heap_B=31604736
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=34
#-----------
time=11897498
mem_heap_B=31600640
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=35
#-----------
time=12590763
mem_heap_B=31604736
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=36
#-----------
time=12895711
mem_heap_B=31600640
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=37
#-----------
time=13246103
mem_heap_B=31604736
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=38
#-----------
time=13401697
mem_heap_B=31600640
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=39
#-----------
time=13420488
mem_heap_B=31604736
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=40
#-----------
time=13590916
mem_heap_B=31600640
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=41
#-----------
time=13692570
mem_heap_B=31604736
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=detailed
n4: 31604736 (page allocation syscalls) mmap/mremap/brk, --alloc-fns, etc.
 n2: 26771456 0x4018429: mmap (syscall-template.S:82)
  n1: 26411008 0x4006B67: _dl_map_object_from_fd (dl-load.c:1283)
   n2: 26411008 0x4008698: _dl_map_object (dl-load.c:2568)
    n1: 24305664 0x400CFE0: openaux (dl-deps.c:65)
     n1: 24305664 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 24305664 0x400D6BC: _dl_map_object_deps (dl-deps.c:258)
       n1: 24305664 0x400350B: dl_main (rtld.c:1826)
        n1: 24305664 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 24305664 0x4005363: _dl_start (rtld.c:338)
          n1: 24305664 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 24305664 0x2: ???
            n1: 24305664 0x7FF0007A5: ???
             n1: 24305664 0x7FF0007AC: ???
              n1: 24305664 0x7FF0007BB: ???
               n0: 24305664 0x7FF0007BD: ???
    n1: 2105344 0x400188C: map_doit (rtld.c:633)
     n1: 2105344 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 2105344 0x4000ECD: do_preload (rtld.c:822)
       n1: 2105344 0x4004118: dl_main (rtld.c:1717)
        n1: 2105344 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 2105344 0x4005363: _dl_start (rtld.c:338)
          n1: 2105344 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 2105344 0x2: ???
            n1: 2105344 0x7FF0007A5: ???
             n1: 2105344 0x7FF0007AC: ???
              n1: 2105344 0x7FF0007BB: ???
               n0: 2105344 0x7FF0007BD: ???
  n0: 360448 in 4 places, all below massif's threshold (01.00%)
 n0: 3239936 0xFFFFFFFFFFFFFFFF: ???
 n2: 1003520 0x5E70169: mmap (syscall-template.S:82)
  n1: 999424 0x5E015CB: _int_malloc (malloc.c:2400)
   n2: 999424 0x5E030B3: malloc (malloc.c:2924)
    n2: 798720 0x423FC6: PyObject_Malloc (in /usr/bin/python2.7)
     n1: 532480 0x54390B: _PyObject_GC_Malloc (in /usr/bin/python2.7)
      n1: 532480 0x4DFB30: PyTuple_New (in /usr/bin/python2.7)
       n0: 532480 in 2 places, all below massif's threshold (01.00%)
     n0: 266240 in 1 place, below massif's threshold (01.00%)
    n0: 200704 in 1 place, below massif's threshold (01.00%)
  n0: 4096 in 1 place, below massif's threshold (01.00%)
 n1: 589824 0x5E6C4D9: brk (brk.c:32)
  n1: 589824 0x5E6C583: sbrk (sbrk.c:54)
   n1: 589824 0x5E057D7: __default_morecore (morecore.c:49)
    n1: 589824 0x5E01178: _int_malloc (malloc.c:2535)
     n2: 589824 0x5E030B3: malloc (malloc.c:2924)
      n1: 319488 0x4F8EBD: ??? (in /usr/bin/python2.7)
       n0: 319488 in 2 places, all below massif's threshold (01.00%)
      n0: 270336 in 2 places, all below massif's threshold (01.00%)
#-----------
snapshot=42
#-----------
time=13999942
mem_heap_B=31600640
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=43
#-----------
time=14018894
mem_heap_B=31604736
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=44
#-----------
time=14167304
mem_heap_B=31600640
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=45
#-----------
time=14325409
mem_heap_B=31735808
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=46
#-----------
time=14487845
mem_heap_B=32002048
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=47
#-----------
time=18609161
mem_heap_B=32006144
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=48
#-----------
time=18912817
mem_heap_B=32006144
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=detailed
n4: 32006144 (page allocation syscalls) mmap/mremap/brk, --alloc-fns, etc.
 n2: 26771456 0x4018429: mmap (syscall-template.S:82)
  n1: 26411008 0x4006B67: _dl_map_object_from_fd (dl-load.c:1283)
   n2: 26411008 0x4008698: _dl_map_object (dl-load.c:2568)
    n1: 24305664 0x400CFE0: openaux (dl-deps.c:65)
     n1: 24305664 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 24305664 0x400D6BC: _dl_map_object_deps (dl-deps.c:258)
       n1: 24305664 0x400350B: dl_main (rtld.c:1826)
        n1: 24305664 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 24305664 0x4005363: _dl_start (rtld.c:338)
          n1: 24305664 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 24305664 0x2: ???
            n1: 24305664 0x7FF0007A5: ???
             n1: 24305664 0x7FF0007AC: ???
              n1: 24305664 0x7FF0007BB: ???
               n0: 24305664 0x7FF0007BD: ???
    n1: 2105344 0x400188C: map_doit (rtld.c:633)
     n1: 2105344 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 2105344 0x4000ECD: do_preload (rtld.c:822)
       n1: 2105344 0x4004118: dl_main (rtld.c:1717)
        n1: 2105344 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 2105344 0x4005363: _dl_start (rtld.c:338)
          n1: 2105344 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 2105344 0x2: ???
            n1: 2105344 0x7FF0007A5: ???
             n1: 2105344 0x7FF0007AC: ???
              n1: 2105344 0x7FF0007BB: ???
               n0: 2105344 0x7FF0007BD: ???
  n0: 360448 in 4 places, all below massif's threshold (01.00%)
 n0: 3239936 0xFFFFFFFFFFFFFFFF: ???
 n2: 1269760 0x5E70169: mmap (syscall-template.S:82)
  n1: 1265664 0x5E015CB: _int_malloc (malloc.c:2400)
   n2: 1265664 0x5E030B3: malloc (malloc.c:2924)
    n2: 1064960 0x423FC6: PyObject_Malloc (in /usr/bin/python2.7)
     n1: 798720 0x54390B: _PyObject_GC_Malloc (in /usr/bin/python2.7)
      n1: 798720 0x4DFB30: PyTuple_New (in /usr/bin/python2.7)
       n0: 798720 in 3 places, all below massif's threshold (01.00%)
     n0: 266240 in 1 place, below massif's threshold (01.00%)
    n0: 200704 in 1 place, below massif's threshold (01.00%)
  n0: 4096 in 1 place, below massif's threshold (01.00%)
 n1: 724992 0x5E6C4D9: brk (brk.c:32)
  n1: 724992 0x5E6C583: sbrk (sbrk.c:54)
   n1: 724992 0x5E057D7: __default_morecore (morecore.c:49)
    n1: 724992 0x5E01178: _int_malloc (malloc.c:2535)
     n2: 724992 0x5E030B3: malloc (malloc.c:2924)
      n1: 454656 0x4F8EBD: ??? (in /usr/bin/python2.7)
       n0: 454656 in 3 places, all below massif's threshold (01.00%)
      n0: 270336 in 2 places, all below massif's threshold (01.00%)
#-----------
snapshot=49
#-----------
time=18912817
mem_heap_B=32002048
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=50
#-----------
time=30771927
mem_heap_B=32006144
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=51
#-----------
time=34257859
mem_heap_B=32153600
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=52
#-----------
time=38944717
mem_heap_B=32149504
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=53
#-----------
time=40028479
mem_heap_B=32153600
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=54
#-----------
time=41563652
mem_heap_B=32149504
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=55
#-----------
time=41578761
mem_heap_B=32153600
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=56
#-----------
time=42012783
mem_heap_B=32149504
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=57
#-----------
time=42027938
mem_heap_B=32153600
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=58
#-----------
time=42461896
mem_heap_B=32149504
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=detailed
n4: 32149504 (page allocation syscalls) mmap/mremap/brk, --alloc-fns, etc.
 n2: 26771456 0x4018429: mmap (syscall-template.S:82)
  n1: 26411008 0x4006B67: _dl_map_object_from_fd (dl-load.c:1283)
   n2: 26411008 0x4008698: _dl_map_object (dl-load.c:2568)
    n1: 24305664 0x400CFE0: openaux (dl-deps.c:65)
     n1: 24305664 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 24305664 0x400D6BC: _dl_map_object_deps (dl-deps.c:258)
       n1: 24305664 0x400350B: dl_main (rtld.c:1826)
        n1: 24305664 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 24305664 0x4005363: _dl_start (rtld.c:338)
          n1: 24305664 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 24305664 0x2: ???
            n1: 24305664 0x7FF0007A5: ???
             n1: 24305664 0x7FF0007AC: ???
              n1: 24305664 0x7FF0007BB: ???
               n0: 24305664 0x7FF0007BD: ???
    n1: 2105344 0x400188C: map_doit (rtld.c:633)
     n1: 2105344 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 2105344 0x4000ECD: do_preload (rtld.c:822)
       n1: 2105344 0x4004118: dl_main (rtld.c:1717)
        n1: 2105344 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 2105344 0x4005363: _dl_start (rtld.c:338)
          n1: 2105344 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 2105344 0x2: ???
            n1: 2105344 0x7FF0007A5: ???
             n1: 2105344 0x7FF0007AC: ???
              n1: 2105344 0x7FF0007BB: ???
               n0: 2105344 0x7FF0007BD: ???
  n0: 360448 in 4 places, all below massif's threshold (01.00%)
 n0: 3239936 0xFFFFFFFFFFFFFFFF: ???
 n2: 1265664 0x5E70169: mmap (syscall-template.S:82)
  n1: 1265664 0x5E015CB: _int_malloc (malloc.c:2400)
   n2: 1265664 0x5E030B3: malloc (malloc.c:2924)
    n2: 1064960 0x423FC6: PyObject_Malloc (in /usr/bin/python2.7)
     n1: 798720 0x54390B: _PyObject_GC_Malloc (in /usr/bin/python2.7)
      n1: 798720 0x4DFB30: PyTuple_New (in /usr/bin/python2.7)
       n0: 798720 in 3 places, all below massif's threshold (01.00%)
     n0: 266240 in 1 place, below massif's threshold (01.00%)
    n0: 200704 in 1 place, below massif's threshold (01.00%)
  n0: 0 in 1 place, below massif's threshold (01.00%)
 n1: 872448 0x5E6C4D9: brk (brk.c:32)
  n1: 872448 0x5E6C583: sbrk (sbrk.c:54)
   n1: 872448 0x5E057D7: __default_morecore (morecore.c:49)
    n1: 872448 0x5E01178: _int_malloc (malloc.c:2535)
     n2: 872448 0x5E030B3: malloc (malloc.c:2924)
      n1: 602112 0x4F8EBD: ??? (in /usr/bin/python2.7)
       n0: 602112 in 4 places, all below massif's threshold (01.00%)
      n0: 270336 in 2 places, all below massif's threshold (01.00%)
#-----------
snapshot=59
#-----------
time=42568016
mem_heap_B=32153600
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=60
#-----------
time=42630202
mem_heap_B=32153600
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=61
#-----------
time=42705063
mem_heap_B=32149504
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=62
#-----------
time=42779533
mem_heap_B=33759232
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=63
#-----------
time=42810175
mem_heap_B=33763328
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=64
#-----------
time=42864600
mem_heap_B=33763328
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=detailed
n4: 33763328 (page allocation syscalls) mmap/mremap/brk, --alloc-fns, etc.
 n2: 26771456 0x4018429: mmap (syscall-template.S:82)
  n1: 26411008 0x4006B67: _dl_map_object_from_fd (dl-load.c:1283)
   n2: 26411008 0x4008698: _dl_map_object (dl-load.c:2568)
    n1: 24305664 0x400CFE0: openaux (dl-deps.c:65)
     n1: 24305664 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 24305664 0x400D6BC: _dl_map_object_deps (dl-deps.c:258)
       n1: 24305664 0x400350B: dl_main (rtld.c:1826)
        n1: 24305664 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 24305664 0x4005363: _dl_start (rtld.c:338)
          n1: 24305664 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 24305664 0x2: ???
            n1: 24305664 0x7FF0007A5: ???
             n1: 24305664 0x7FF0007AC: ???
              n1: 24305664 0x7FF0007BB: ???
               n0: 24305664 0x7FF0007BD: ???
    n1: 2105344 0x400188C: map_doit (rtld.c:633)
     n1: 2105344 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 2105344 0x4000ECD: do_preload (rtld.c:822)
       n1: 2105344 0x4004118: dl_main (rtld.c:1717)
        n1: 2105344 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 2105344 0x4005363: _dl_start (rtld.c:338)
          n1: 2105344 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 2105344 0x2: ???
            n1: 2105344 0x7FF0007A5: ???
             n1: 2105344 0x7FF0007AC: ???
              n1: 2105344 0x7FF0007BB: ???
               n0: 2105344 0x7FF0007BD: ???
  n0: 360448 in 4 places, all below massif's threshold (01.00%)
 n0: 3239936 0xFFFFFFFFFFFFFFFF: ???
 n3: 2879488 0x5E70169: mmap (syscall-template.S:82)
  n1: 1609728 0x5DADDC4: _nl_load_locale_from_archive (loadarchive.c:228)
   n1: 1609728 0x5DACE11: _nl_find_locale (findlocale.c:107)
    n1: 1609728 0x5DAC4F8: setlocale (setlocale.c:379)
     n1: 1609728 0x52D353: ??? (in /usr/bin/python2.7)
      n1: 1609728 0x4AA66B: Py_Main (in /usr/bin/python2.7)
       n0: 1609728 0x5DA176B: (below main) (libc-start.c:226)
  n1: 1265664 0x5E015CB: _int_malloc (malloc.c:2400)
   n2: 1265664 0x5E030B3: malloc (malloc.c:2924)
    n2: 1064960 0x423FC6: PyObject_Malloc (in /usr/bin/python2.7)
     n1: 798720 0x54390B: _PyObject_GC_Malloc (in /usr/bin/python2.7)
      n1: 798720 0x4DFB30: PyTuple_New (in /usr/bin/python2.7)
       n0: 798720 in 3 places, all below massif's threshold (01.00%)
     n0: 266240 in 1 place, below massif's threshold (01.00%)
    n0: 200704 in 1 place, below massif's threshold (01.00%)
  n0: 4096 in 1 place, below massif's threshold (01.00%)
 n1: 872448 0x5E6C4D9: brk (brk.c:32)
  n1: 872448 0x5E6C583: sbrk (sbrk.c:54)
   n1: 872448 0x5E057D7: __default_morecore (morecore.c:49)
    n1: 872448 0x5E01178: _int_malloc (malloc.c:2535)
     n2: 872448 0x5E030B3: malloc (malloc.c:2924)
      n1: 602112 0x4F8EBD: ??? (in /usr/bin/python2.7)
       n0: 602112 in 4 places, all below massif's threshold (01.00%)
      n0: 270336 in 2 places, all below massif's threshold (01.00%)
#-----------
snapshot=65
#-----------
time=42889419
mem_heap_B=33763328
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=66
#-----------
time=43416054
mem_heap_B=33759232
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=67
#-----------
time=43926373
mem_heap_B=33763328
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=68
#-----------
time=44225551
mem_heap_B=33759232
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=69
#-----------
time=44443963
mem_heap_B=33898496
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=70
#-----------
time=44489154
mem_heap_B=33894400
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=71
#-----------
time=44689546
mem_heap_B=33898496
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=72
#-----------
time=45066889
mem_heap_B=33894400
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=73
#-----------
time=45230632
mem_heap_B=33898496
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=74
#-----------
time=45319315
mem_heap_B=33894400
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=detailed
n4: 33894400 (page allocation syscalls) mmap/mremap/brk, --alloc-fns, etc.
 n2: 26771456 0x4018429: mmap (syscall-template.S:82)
  n1: 26411008 0x4006B67: _dl_map_object_from_fd (dl-load.c:1283)
   n2: 26411008 0x4008698: _dl_map_object (dl-load.c:2568)
    n1: 24305664 0x400CFE0: openaux (dl-deps.c:65)
     n1: 24305664 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 24305664 0x400D6BC: _dl_map_object_deps (dl-deps.c:258)
       n1: 24305664 0x400350B: dl_main (rtld.c:1826)
        n1: 24305664 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 24305664 0x4005363: _dl_start (rtld.c:338)
          n1: 24305664 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 24305664 0x2: ???
            n1: 24305664 0x7FF0007A5: ???
             n1: 24305664 0x7FF0007AC: ???
              n1: 24305664 0x7FF0007BB: ???
               n0: 24305664 0x7FF0007BD: ???
    n1: 2105344 0x400188C: map_doit (rtld.c:633)
     n1: 2105344 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 2105344 0x4000ECD: do_preload (rtld.c:822)
       n1: 2105344 0x4004118: dl_main (rtld.c:1717)
        n1: 2105344 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 2105344 0x4005363: _dl_start (rtld.c:338)
          n1: 2105344 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 2105344 0x2: ???
            n1: 2105344 0x7FF0007A5: ???
             n1: 2105344 0x7FF0007AC: ???
              n1: 2105344 0x7FF0007BB: ???
               n0: 2105344 0x7FF0007BD: ???
  n0: 360448 in 4 places, all below massif's threshold (01.00%)
 n0: 3239936 0xFFFFFFFFFFFFFFFF: ???
 n3: 2875392 0x5E70169: mmap (syscall-template.S:82)
  n1: 1609728 0x5DADDC4: _nl_load_locale_from_archive (loadarchive.c:228)
   n1: 1609728 0x5DACE11: _nl_find_locale (findlocale.c:107)
    n1: 1609728 0x5DAC4F8: setlocale (setlocale.c:379)
     n1: 1609728 0x52D353: ??? (in /usr/bin/python2.7)
      n1: 1609728 0x4AA66B: Py_Main (in /usr/bin/python2.7)
       n0: 1609728 0x5DA176B: (below main) (libc-start.c:226)
  n1: 1265664 0x5E015CB: _int_malloc (malloc.c:2400)
   n2: 1265664 0x5E030B3: malloc (malloc.c:2924)
    n2: 1064960 0x423FC6: PyObject_Malloc (in /usr/bin/python2.7)
     n1: 798720 0x54390B: _PyObject_GC_Malloc (in /usr/bin/python2.7)
      n1: 798720 0x4DFB30: PyTuple_New (in /usr/bin/python2.7)
       n0: 798720 in 3 places, all below massif's threshold (01.00%)
     n0: 266240 in 1 place, below massif's threshold (01.00%)
    n0: 200704 in 1 place, below massif's threshold (01.00%)
  n0: 0 in 1 place, below massif's threshold (01.00%)
 n1: 1007616 0x5E6C4D9: brk (brk.c:32)
  n1: 1007616 0x5E6C583: sbrk (sbrk.c:54)
   n1: 1007616 0x5E057D7: __default_morecore (morecore.c:49)
    n1: 1007616 0x5E01178: _int_malloc (malloc.c:2535)
     n2: 1007616 0x5E030B3: malloc (malloc.c:2924)
      n1: 737280 0x4F8EBD: ??? (in /usr/bin/python2.7)
       n0: 737280 in 5 places, all below massif's threshold (01.00%)
      n0: 270336 in 2 places, all below massif's threshold (01.00%)
#-----------
snapshot=75
#-----------
time=45346455
mem_heap_B=36036608
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=76
#-----------
time=45361555
mem_heap_B=48738304
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=77
#-----------
time=45665734
mem_heap_B=57139200
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=78
#-----------
time=45672118
mem_heap_B=57118720
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=detailed
n4: 57118720 (page allocation syscalls) mmap/mremap/brk, --alloc-fns, etc.
 n3: 41603072 0x4018429: mmap (syscall-template.S:82)
  n1: 37015552 0x4006B67: _dl_map_object_from_fd (dl-load.c:1283)
   n3: 37015552 0x4008698: _dl_map_object (dl-load.c:2568)
    n1: 32768000 0x400CFE0: openaux (dl-deps.c:65)
     n1: 32768000 0x400F174: _dl_catch_error (dl-error.c:178)
      n2: 32768000 0x400D6BC: _dl_map_object_deps (dl-deps.c:258)
       n1: 24305664 0x400350B: dl_main (rtld.c:1826)
        n1: 24305664 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 24305664 0x4005363: _dl_start (rtld.c:338)
          n1: 24305664 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 24305664 0x2: ???
            n1: 24305664 0x7FF0007A5: ???
             n1: 24305664 0x7FF0007AC: ???
              n1: 24305664 0x7FF0007BB: ???
               n0: 24305664 0x7FF0007BD: ???
       n1: 8462336 0x40138A7: dl_open_worker (dl-open.c:262)
        n1: 8462336 0x400F174: _dl_catch_error (dl-error.c:178)
         n1: 8462336 0x4013318: _dl_open (dl-open.c:639)
          n1: 8462336 0x4E44F24: dlopen_doit (dlopen.c:67)
           n1: 8462336 0x400F174: _dl_catch_error (dl-error.c:178)
            n1: 8462336 0x4E4552D: _dlerror_run (dlerror.c:164)
             n1: 8462336 0x4E44FBF: dlopen@@GLIBC_2.2.5 (dlopen.c:88)
              n1: 8462336 0x561838: _PyImport_GetDynLoadFunc (in /usr/bin/python2.7)
               n1: 8462336 0x47AF17: _PyImport_LoadDynamicModule (in /usr/bin/python2.7)
                n1: 8462336 0x53D7D9: ??? (in /usr/bin/python2.7)
                 n1: 8462336 0x53DCA8: ??? (in /usr/bin/python2.7)
                  n1: 8462336 0x53E1B1: ??? (in /usr/bin/python2.7)
                   n1: 8462336 0x4C2E69: ??? (in /usr/bin/python2.7)
                    n1: 8462336 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                     n1: 8462336 0x4EA394: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
                      n1: 8462336 0x49A4EB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
                       n1: 8462336 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
                        n1: 8462336 0x4A7F16: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
                         n1: 8462336 0x53CDDF: ??? (in /usr/bin/python2.7)
                          n1: 8462336 0x4A4189: ??? (in /usr/bin/python2.7)
                           n1: 8462336 0x53D7D9: ??? (in /usr/bin/python2.7)
                            n1: 8462336 0x4FC1A1: ??? (in /usr/bin/python2.7)
                             n1: 8462336 0x53E0A2: ??? (in /usr/bin/python2.7)
                              n0: 8462336 0x4C2E69: ??? (in /usr/bin/python2.7)
    n1: 2142208 0x4013849: dl_open_worker (dl-open.c:225)
     n1: 2142208 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 2142208 0x4013318: _dl_open (dl-open.c:639)
       n1: 2142208 0x4E44F24: dlopen_doit (dlopen.c:67)
        n1: 2142208 0x400F174: _dl_catch_error (dl-error.c:178)
         n1: 2142208 0x4E4552D: _dlerror_run (dlerror.c:164)
          n1: 2142208 0x4E44FBF: dlopen@@GLIBC_2.2.5 (dlopen.c:88)
           n1: 2142208 0x561838: _PyImport_GetDynLoadFunc (in /usr/bin/python2.7)
            n1: 2142208 0x47AF17: _PyImport_LoadDynamicModule (in /usr/bin/python2.7)
             n1: 2142208 0x53D7D9: ??? (in /usr/bin/python2.7)
              n1: 2142208 0x53DCA8: ??? (in /usr/bin/python2.7)
               n1: 2142208 0x53E1B1: ??? (in /usr/bin/python2.7)
                n1: 2142208 0x4C2E69: ??? (in /usr/bin/python2.7)
                 n1: 2142208 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                  n1: 2142208 0x4EA394: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
                   n1: 2142208 0x49A4EB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
                    n1: 2142208 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
                     n1: 2142208 0x4A7F16: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
                      n1: 2142208 0x53CDDF: ??? (in /usr/bin/python2.7)
                       n1: 2142208 0x4A4189: ??? (in /usr/bin/python2.7)
                        n1: 2142208 0x53D7D9: ??? (in /usr/bin/python2.7)
                         n1: 2142208 0x4FC1A1: ??? (in /usr/bin/python2.7)
                          n1: 2142208 0x53E0A2: ??? (in /usr/bin/python2.7)
                           n1: 2142208 0x4C2E69: ??? (in /usr/bin/python2.7)
                            n1: 2142208 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                             n1: 2142208 0x4EA394: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
                              n0: 2142208 0x49A4EB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
    n1: 2105344 0x400188C: map_doit (rtld.c:633)
     n1: 2105344 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 2105344 0x4000ECD: do_preload (rtld.c:822)
       n1: 2105344 0x4004118: dl_main (rtld.c:1717)
        n1: 2105344 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 2105344 0x4005363: _dl_start (rtld.c:338)
          n1: 2105344 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 2105344 0x2: ???
            n1: 2105344 0x7FF0007A5: ???
             n1: 2105344 0x7FF0007AC: ???
              n1: 2105344 0x7FF0007BB: ???
               n0: 2105344 0x7FF0007BD: ???
  n1: 4251648 0x4007148: _dl_map_object_from_fd (dl-load.c:1392)
   n1: 4251648 0x4008698: _dl_map_object (dl-load.c:2568)
    n1: 4251648 0x400CFE0: openaux (dl-deps.c:65)
     n1: 4251648 0x400F174: _dl_catch_error (dl-error.c:178)
      n2: 4251648 0x400D6BC: _dl_map_object_deps (dl-deps.c:258)
       n1: 4194304 0x40138A7: dl_open_worker (dl-open.c:262)
        n1: 4194304 0x400F174: _dl_catch_error (dl-error.c:178)
         n1: 4194304 0x4013318: _dl_open (dl-open.c:639)
          n1: 4194304 0x4E44F24: dlopen_doit (dlopen.c:67)
           n1: 4194304 0x400F174: _dl_catch_error (dl-error.c:178)
            n1: 4194304 0x4E4552D: _dlerror_run (dlerror.c:164)
             n1: 4194304 0x4E44FBF: dlopen@@GLIBC_2.2.5 (dlopen.c:88)
              n1: 4194304 0x561838: _PyImport_GetDynLoadFunc (in /usr/bin/python2.7)
               n1: 4194304 0x47AF17: _PyImport_LoadDynamicModule (in /usr/bin/python2.7)
                n1: 4194304 0x53D7D9: ??? (in /usr/bin/python2.7)
                 n1: 4194304 0x53DCA8: ??? (in /usr/bin/python2.7)
                  n1: 4194304 0x53E1B1: ??? (in /usr/bin/python2.7)
                   n1: 4194304 0x4C2E69: ??? (in /usr/bin/python2.7)
                    n1: 4194304 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                     n1: 4194304 0x4EA394: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
                      n1: 4194304 0x49A4EB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
                       n1: 4194304 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
                        n1: 4194304 0x4A7F16: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
                         n1: 4194304 0x53CDDF: ??? (in /usr/bin/python2.7)
                          n1: 4194304 0x4A4189: ??? (in /usr/bin/python2.7)
                           n1: 4194304 0x53D7D9: ??? (in /usr/bin/python2.7)
                            n1: 4194304 0x4FC1A1: ??? (in /usr/bin/python2.7)
                             n1: 4194304 0x53E0A2: ??? (in /usr/bin/python2.7)
                              n0: 4194304 0x4C2E69: ??? (in /usr/bin/python2.7)
       n0: 57344 in 1 place, below massif's threshold (01.00%)
  n0: 335872 in 3 places, all below massif's threshold (01.00%)
 n4: 11268096 0x5E70169: mmap (syscall-template.S:82)
  n1: 8392704 0x4C2FA2C: pthread_create@@GLIBC_2.2.5 (allocatestack.c:495)
   n1: 8392704 0x400F304: call_init.part.0 (dl-init.c:85)
    n1: 8392704 0x400F3DD: _dl_init (dl-init.c:52)
     n1: 8392704 0x4013AD8: dl_open_worker (dl-open.c:549)
      n1: 8392704 0x400F174: _dl_catch_error (dl-error.c:178)
       n1: 8392704 0x4013318: _dl_open (dl-open.c:639)
        n1: 8392704 0x4E44F24: dlopen_doit (dlopen.c:67)
         n1: 8392704 0x400F174: _dl_catch_error (dl-error.c:178)
          n1: 8392704 0x4E4552D: _dlerror_run (dlerror.c:164)
           n1: 8392704 0x4E44FBF: dlopen@@GLIBC_2.2.5 (dlopen.c:88)
            n1: 8392704 0x561838: _PyImport_GetDynLoadFunc (in /usr/bin/python2.7)
             n1: 8392704 0x47AF17: _PyImport_LoadDynamicModule (in /usr/bin/python2.7)
              n1: 8392704 0x53D7D9: ??? (in /usr/bin/python2.7)
               n1: 8392704 0x53DCA8: ??? (in /usr/bin/python2.7)
                n1: 8392704 0x53E1B1: ??? (in /usr/bin/python2.7)
                 n1: 8392704 0x4C2E69: ??? (in /usr/bin/python2.7)
                  n1: 8392704 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                   n1: 8392704 0x4EA394: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
                    n1: 8392704 0x49A4EB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
                     n1: 8392704 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
                      n1: 8392704 0x4A7F16: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
                       n1: 8392704 0x53CDDF: ??? (in /usr/bin/python2.7)
                        n1: 8392704 0x4A4189: ??? (in /usr/bin/python2.7)
                         n1: 8392704 0x53D7D9: ??? (in /usr/bin/python2.7)
                          n1: 8392704 0x4FC1A1: ??? (in /usr/bin/python2.7)
                           n1: 8392704 0x53E0A2: ??? (in /usr/bin/python2.7)
                            n1: 8392704 0x4C2E69: ??? (in /usr/bin/python2.7)
                             n1: 8392704 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                              n0: 8392704 0x4EA394: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
  n1: 1609728 0x5DADDC4: _nl_load_locale_from_archive (loadarchive.c:228)
   n1: 1609728 0x5DACE11: _nl_find_locale (findlocale.c:107)
    n1: 1609728 0x5DAC4F8: setlocale (setlocale.c:379)
     n1: 1609728 0x52D353: ??? (in /usr/bin/python2.7)
      n1: 1609728 0x4AA66B: Py_Main (in /usr/bin/python2.7)
       n0: 1609728 0x5DA176B: (below main) (libc-start.c:226)
  n1: 1265664 0x5E015CB: _int_malloc (malloc.c:2400)
   n2: 1265664 0x5E030B3: malloc (malloc.c:2924)
    n2: 1064960 0x423FC6: PyObject_Malloc (in /usr/bin/python2.7)
     n1: 798720 0x54390B: _PyObject_GC_Malloc (in /usr/bin/python2.7)
      n1: 798720 0x4DFB30: PyTuple_New (in /usr/bin/python2.7)
       n0: 798720 in 3 places, all below massif's threshold (01.00%)
     n0: 266240 in 1 place, below massif's threshold (01.00%)
    n0: 200704 in 1 place, below massif's threshold (01.00%)
  n0: 0 in 1 place, below massif's threshold (01.00%)
 n0: 3239936 0xFFFFFFFFFFFFFFFF: ???
 n1: 1007616 0x5E6C4D9: brk (brk.c:32)
  n1: 1007616 0x5E6C583: sbrk (sbrk.c:54)
   n1: 1007616 0x5E057D7: __default_morecore (morecore.c:49)
    n1: 1007616 0x5E01178: _int_malloc (malloc.c:2535)
     n2: 1007616 0x5E030B3: malloc (malloc.c:2924)
      n1: 737280 0x4F8EBD: ??? (in /usr/bin/python2.7)
       n0: 737280 in 5 places, all below massif's threshold (01.00%)
      n0: 270336 in 2 places, all below massif's threshold (01.00%)
#-----------
snapshot=79
#-----------
time=45973837
mem_heap_B=57450496
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=80
#-----------
time=46144247
mem_heap_B=57454592
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=81
#-----------
time=46161581
mem_heap_B=57475072
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=82
#-----------
time=46212595
mem_heap_B=61816832
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=detailed
n4: 61816832 (page allocation syscalls) mmap/mremap/brk, --alloc-fns, etc.
 n3: 45965312 0x4018429: mmap (syscall-template.S:82)
  n1: 41353216 0x4006B67: _dl_map_object_from_fd (dl-load.c:1283)
   n3: 41353216 0x4008698: _dl_map_object (dl-load.c:2568)
    n1: 34971648 0x400CFE0: openaux (dl-deps.c:65)
     n1: 34971648 0x400F174: _dl_catch_error (dl-error.c:178)
      n2: 34971648 0x400D6BC: _dl_map_object_deps (dl-deps.c:258)
       n1: 24305664 0x400350B: dl_main (rtld.c:1826)
        n1: 24305664 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 24305664 0x4005363: _dl_start (rtld.c:338)
          n1: 24305664 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 24305664 0x2: ???
            n1: 24305664 0x7FF0007A5: ???
             n1: 24305664 0x7FF0007AC: ???
              n1: 24305664 0x7FF0007BB: ???
               n0: 24305664 0x7FF0007BD: ???
       n1: 10665984 0x40138A7: dl_open_worker (dl-open.c:262)
        n1: 10665984 0x400F174: _dl_catch_error (dl-error.c:178)
         n2: 10665984 0x4013318: _dl_open (dl-open.c:639)
          n1: 8462336 0x4E44F24: dlopen_doit (dlopen.c:67)
           n1: 8462336 0x400F174: _dl_catch_error (dl-error.c:178)
            n1: 8462336 0x4E4552D: _dlerror_run (dlerror.c:164)
             n1: 8462336 0x4E44FBF: dlopen@@GLIBC_2.2.5 (dlopen.c:88)
              n1: 8462336 0x561838: _PyImport_GetDynLoadFunc (in /usr/bin/python2.7)
               n1: 8462336 0x47AF17: _PyImport_LoadDynamicModule (in /usr/bin/python2.7)
                n1: 8462336 0x53D7D9: ??? (in /usr/bin/python2.7)
                 n1: 8462336 0x53DCA8: ??? (in /usr/bin/python2.7)
                  n1: 8462336 0x53E1B1: ??? (in /usr/bin/python2.7)
                   n1: 8462336 0x4C2E69: ??? (in /usr/bin/python2.7)
                    n1: 8462336 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                     n1: 8462336 0x4EA394: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
                      n1: 8462336 0x49A4EB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
                       n1: 8462336 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
                        n1: 8462336 0x4A7F16: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
                         n1: 8462336 0x53CDDF: ??? (in /usr/bin/python2.7)
                          n1: 8462336 0x4A4189: ??? (in /usr/bin/python2.7)
                           n1: 8462336 0x53D7D9: ??? (in /usr/bin/python2.7)
                            n1: 8462336 0x4FC1A1: ??? (in /usr/bin/python2.7)
                             n1: 8462336 0x53E0A2: ??? (in /usr/bin/python2.7)
                              n0: 8462336 0x4C2E69: ??? (in /usr/bin/python2.7)
          n1: 2203648 0x5EB0700: do_dlopen (dl-libc.c:89)
           n1: 2203648 0x400F174: _dl_catch_error (dl-error.c:178)
            n1: 2203648 0x5EB07C2: __libc_dlopen_mode (dl-libc.c:48)
             n1: 2203648 0x5E85B1C: nss_load_library.isra.1 (nsswitch.c:372)
              n1: 2203648 0x5E8657B: __nss_lookup_function (nsswitch.c:474)
               n1: 2203648 0x5E8678A: __nss_lookup (nsswitch.c:202)
                n1: 2203648 0x5E3EE16: getpwuid_r@@GLIBC_2.2.5 (getXXbyYY_r.c:203)
                 n1: 2203648 0x5E3E5F1: getpwuid (getXXbyYY.c:117)
                  n1: 2203648 0x66EFD6F: sandbox_check (in /usr/lib/libsandbox.so.0.3.5)
                   n1: 2203648 0x64E2D1E: Sandbox_new (in /usr/local/lib/python2.7/dist-packages/sandbox/_sandbox.so)
                    n1: 2203648 0x4DB5E6: ??? (in /usr/bin/python2.7)
                     n1: 2203648 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                      n1: 2203648 0x498468: PyEval_EvalFrameEx (in /usr/bin/python2.7)
                       n1: 2203648 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
                        n1: 2203648 0x4A907F: PyRun_FileExFlags (in /usr/bin/python2.7)
                         n1: 2203648 0x4A930F: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
                          n1: 2203648 0x4AA8BB: Py_Main (in /usr/bin/python2.7)
                           n0: 2203648 0x5DA176B: (below main) (libc-start.c:226)
    n1: 4276224 0x4013849: dl_open_worker (dl-open.c:225)
     n1: 4276224 0x400F174: _dl_catch_error (dl-error.c:178)
      n2: 4276224 0x4013318: _dl_open (dl-open.c:639)
       n1: 2142208 0x4E44F24: dlopen_doit (dlopen.c:67)
        n1: 2142208 0x400F174: _dl_catch_error (dl-error.c:178)
         n1: 2142208 0x4E4552D: _dlerror_run (dlerror.c:164)
          n1: 2142208 0x4E44FBF: dlopen@@GLIBC_2.2.5 (dlopen.c:88)
           n1: 2142208 0x561838: _PyImport_GetDynLoadFunc (in /usr/bin/python2.7)
            n1: 2142208 0x47AF17: _PyImport_LoadDynamicModule (in /usr/bin/python2.7)
             n1: 2142208 0x53D7D9: ??? (in /usr/bin/python2.7)
              n1: 2142208 0x53DCA8: ??? (in /usr/bin/python2.7)
               n1: 2142208 0x53E1B1: ??? (in /usr/bin/python2.7)
                n1: 2142208 0x4C2E69: ??? (in /usr/bin/python2.7)
                 n1: 2142208 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                  n1: 2142208 0x4EA394: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
                   n1: 2142208 0x49A4EB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
                    n1: 2142208 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
                     n1: 2142208 0x4A7F16: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
                      n1: 2142208 0x53CDDF: ??? (in /usr/bin/python2.7)
                       n1: 2142208 0x4A4189: ??? (in /usr/bin/python2.7)
                        n1: 2142208 0x53D7D9: ??? (in /usr/bin/python2.7)
                         n1: 2142208 0x4FC1A1: ??? (in /usr/bin/python2.7)
                          n1: 2142208 0x53E0A2: ??? (in /usr/bin/python2.7)
                           n1: 2142208 0x4C2E69: ??? (in /usr/bin/python2.7)
                            n1: 2142208 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                             n1: 2142208 0x4EA394: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
                              n0: 2142208 0x49A4EB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
       n1: 2134016 0x5EB0700: do_dlopen (dl-libc.c:89)
        n1: 2134016 0x400F174: _dl_catch_error (dl-error.c:178)
         n1: 2134016 0x5EB07C2: __libc_dlopen_mode (dl-libc.c:48)
          n1: 2134016 0x5E85B1C: nss_load_library.isra.1 (nsswitch.c:372)
           n1: 2134016 0x5E8657B: __nss_lookup_function (nsswitch.c:474)
            n1: 2134016 0x5E8678A: __nss_lookup (nsswitch.c:202)
             n1: 2134016 0x5E3EE16: getpwuid_r@@GLIBC_2.2.5 (getXXbyYY_r.c:203)
              n1: 2134016 0x5E3E5F1: getpwuid (getXXbyYY.c:117)
               n1: 2134016 0x66EFD6F: sandbox_check (in /usr/lib/libsandbox.so.0.3.5)
                n1: 2134016 0x64E2D1E: Sandbox_new (in /usr/local/lib/python2.7/dist-packages/sandbox/_sandbox.so)
                 n1: 2134016 0x4DB5E6: ??? (in /usr/bin/python2.7)
                  n1: 2134016 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                   n1: 2134016 0x498468: PyEval_EvalFrameEx (in /usr/bin/python2.7)
                    n1: 2134016 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
                     n1: 2134016 0x4A907F: PyRun_FileExFlags (in /usr/bin/python2.7)
                      n1: 2134016 0x4A930F: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
                       n1: 2134016 0x4AA8BB: Py_Main (in /usr/bin/python2.7)
                        n0: 2134016 0x5DA176B: (below main) (libc-start.c:226)
    n1: 2105344 0x400188C: map_doit (rtld.c:633)
     n1: 2105344 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 2105344 0x4000ECD: do_preload (rtld.c:822)
       n1: 2105344 0x4004118: dl_main (rtld.c:1717)
        n1: 2105344 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 2105344 0x4005363: _dl_start (rtld.c:338)
          n1: 2105344 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 2105344 0x2: ???
            n1: 2105344 0x7FF0007A5: ???
             n1: 2105344 0x7FF0007AC: ???
              n1: 2105344 0x7FF0007BB: ???
               n0: 2105344 0x7FF0007BD: ???
  n1: 4259840 0x4007148: _dl_map_object_from_fd (dl-load.c:1392)
   n1: 4259840 0x4008698: _dl_map_object (dl-load.c:2568)
    n1: 4259840 0x400CFE0: openaux (dl-deps.c:65)
     n1: 4259840 0x400F174: _dl_catch_error (dl-error.c:178)
      n2: 4259840 0x400D6BC: _dl_map_object_deps (dl-deps.c:258)
       n1: 4202496 0x40138A7: dl_open_worker (dl-open.c:262)
        n1: 4202496 0x400F174: _dl_catch_error (dl-error.c:178)
         n2: 4202496 0x4013318: _dl_open (dl-open.c:639)
          n1: 4194304 0x4E44F24: dlopen_doit (dlopen.c:67)
           n1: 4194304 0x400F174: _dl_catch_error (dl-error.c:178)
            n1: 4194304 0x4E4552D: _dlerror_run (dlerror.c:164)
             n1: 4194304 0x4E44FBF: dlopen@@GLIBC_2.2.5 (dlopen.c:88)
              n1: 4194304 0x561838: _PyImport_GetDynLoadFunc (in /usr/bin/python2.7)
               n1: 4194304 0x47AF17: _PyImport_LoadDynamicModule (in /usr/bin/python2.7)
                n1: 4194304 0x53D7D9: ??? (in /usr/bin/python2.7)
                 n1: 4194304 0x53DCA8: ??? (in /usr/bin/python2.7)
                  n1: 4194304 0x53E1B1: ??? (in /usr/bin/python2.7)
                   n1: 4194304 0x4C2E69: ??? (in /usr/bin/python2.7)
                    n1: 4194304 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                     n1: 4194304 0x4EA394: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
                      n1: 4194304 0x49A4EB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
                       n1: 4194304 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
                        n1: 4194304 0x4A7F16: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
                         n1: 4194304 0x53CDDF: ??? (in /usr/bin/python2.7)
                          n1: 4194304 0x4A4189: ??? (in /usr/bin/python2.7)
                           n1: 4194304 0x53D7D9: ??? (in /usr/bin/python2.7)
                            n1: 4194304 0x4FC1A1: ??? (in /usr/bin/python2.7)
                             n1: 4194304 0x53E0A2: ??? (in /usr/bin/python2.7)
                              n0: 4194304 0x4C2E69: ??? (in /usr/bin/python2.7)
          n0: 8192 in 1 place, below massif's threshold (01.00%)
       n0: 57344 in 1 place, below massif's threshold (01.00%)
  n0: 352256 in 3 places, all below massif's threshold (01.00%)
 n4: 11603968 0x5E70169: mmap (syscall-template.S:82)
  n1: 8392704 0x4C2FA2C: pthread_create@@GLIBC_2.2.5 (allocatestack.c:495)
   n1: 8392704 0x400F304: call_init.part.0 (dl-init.c:85)
    n1: 8392704 0x400F3DD: _dl_init (dl-init.c:52)
     n1: 8392704 0x4013AD8: dl_open_worker (dl-open.c:549)
      n1: 8392704 0x400F174: _dl_catch_error (dl-error.c:178)
       n1: 8392704 0x4013318: _dl_open (dl-open.c:639)
        n1: 8392704 0x4E44F24: dlopen_doit (dlopen.c:67)
         n1: 8392704 0x400F174: _dl_catch_error (dl-error.c:178)
          n1: 8392704 0x4E4552D: _dlerror_run (dlerror.c:164)
           n1: 8392704 0x4E44FBF: dlopen@@GLIBC_2.2.5 (dlopen.c:88)
            n1: 8392704 0x561838: _PyImport_GetDynLoadFunc (in /usr/bin/python2.7)
             n1: 8392704 0x47AF17: _PyImport_LoadDynamicModule (in /usr/bin/python2.7)
              n1: 8392704 0x53D7D9: ??? (in /usr/bin/python2.7)
               n1: 8392704 0x53DCA8: ??? (in /usr/bin/python2.7)
                n1: 8392704 0x53E1B1: ??? (in /usr/bin/python2.7)
                 n1: 8392704 0x4C2E69: ??? (in /usr/bin/python2.7)
                  n1: 8392704 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                   n1: 8392704 0x4EA394: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
                    n1: 8392704 0x49A4EB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
                     n1: 8392704 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
                      n1: 8392704 0x4A7F16: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
                       n1: 8392704 0x53CDDF: ??? (in /usr/bin/python2.7)
                        n1: 8392704 0x4A4189: ??? (in /usr/bin/python2.7)
                         n1: 8392704 0x53D7D9: ??? (in /usr/bin/python2.7)
                          n1: 8392704 0x4FC1A1: ??? (in /usr/bin/python2.7)
                           n1: 8392704 0x53E0A2: ??? (in /usr/bin/python2.7)
                            n1: 8392704 0x4C2E69: ??? (in /usr/bin/python2.7)
                             n1: 8392704 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                              n0: 8392704 0x4EA394: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
  n1: 1609728 0x5DADDC4: _nl_load_locale_from_archive (loadarchive.c:228)
   n1: 1609728 0x5DACE11: _nl_find_locale (findlocale.c:107)
    n1: 1609728 0x5DAC4F8: setlocale (setlocale.c:379)
     n1: 1609728 0x52D353: ??? (in /usr/bin/python2.7)
      n1: 1609728 0x4AA66B: Py_Main (in /usr/bin/python2.7)
       n0: 1609728 0x5DA176B: (below main) (libc-start.c:226)
  n1: 1601536 0x5E015CB: _int_malloc (malloc.c:2400)
   n2: 1601536 0x5E030B3: malloc (malloc.c:2924)
    n2: 1064960 0x423FC6: PyObject_Malloc (in /usr/bin/python2.7)
     n1: 798720 0x54390B: _PyObject_GC_Malloc (in /usr/bin/python2.7)
      n1: 798720 0x4DFB30: PyTuple_New (in /usr/bin/python2.7)
       n0: 798720 in 3 places, all below massif's threshold (01.00%)
     n0: 266240 in 1 place, below massif's threshold (01.00%)
    n0: 536576 in 2 places, all below massif's threshold (01.00%)
  n0: 0 in 1 place, below massif's threshold (01.00%)
 n0: 3239936 0xFFFFFFFFFFFFFFFF: ???
 n1: 1007616 0x5E6C4D9: brk (brk.c:32)
  n1: 1007616 0x5E6C583: sbrk (sbrk.c:54)
   n1: 1007616 0x5E057D7: __default_morecore (morecore.c:49)
    n1: 1007616 0x5E01178: _int_malloc (malloc.c:2535)
     n2: 1007616 0x5E030B3: malloc (malloc.c:2924)
      n1: 737280 0x4F8EBD: ??? (in /usr/bin/python2.7)
       n0: 737280 in 5 places, all below massif's threshold (01.00%)
      n0: 270336 in 2 places, all below massif's threshold (01.00%)
#-----------
snapshot=83
#-----------
time=46236456
mem_heap_B=66142208
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=84
#-----------
time=46274177
mem_heap_B=66129920
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=detailed
n4: 66129920 (page allocation syscalls) mmap/mremap/brk, --alloc-fns, etc.
 n3: 50278400 0x4018429: mmap (syscall-template.S:82)
  n1: 45649920 0x4006B67: _dl_map_object_from_fd (dl-load.c:1283)
   n3: 45649920 0x4008698: _dl_map_object (dl-load.c:2568)
    n1: 37122048 0x400CFE0: openaux (dl-deps.c:65)
     n1: 37122048 0x400F174: _dl_catch_error (dl-error.c:178)
      n2: 37122048 0x400D6BC: _dl_map_object_deps (dl-deps.c:258)
       n1: 24305664 0x400350B: dl_main (rtld.c:1826)
        n1: 24305664 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 24305664 0x4005363: _dl_start (rtld.c:338)
          n1: 24305664 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 24305664 0x2: ???
            n1: 24305664 0x7FF0007A5: ???
             n1: 24305664 0x7FF0007AC: ???
              n1: 24305664 0x7FF0007BB: ???
               n0: 24305664 0x7FF0007BD: ???
       n1: 12816384 0x40138A7: dl_open_worker (dl-open.c:262)
        n1: 12816384 0x400F174: _dl_catch_error (dl-error.c:178)
         n2: 12816384 0x4013318: _dl_open (dl-open.c:639)
          n1: 8462336 0x4E44F24: dlopen_doit (dlopen.c:67)
           n1: 8462336 0x400F174: _dl_catch_error (dl-error.c:178)
            n1: 8462336 0x4E4552D: _dlerror_run (dlerror.c:164)
             n1: 8462336 0x4E44FBF: dlopen@@GLIBC_2.2.5 (dlopen.c:88)
              n1: 8462336 0x561838: _PyImport_GetDynLoadFunc (in /usr/bin/python2.7)
               n1: 8462336 0x47AF17: _PyImport_LoadDynamicModule (in /usr/bin/python2.7)
                n1: 8462336 0x53D7D9: ??? (in /usr/bin/python2.7)
                 n1: 8462336 0x53DCA8: ??? (in /usr/bin/python2.7)
                  n1: 8462336 0x53E1B1: ??? (in /usr/bin/python2.7)
                   n1: 8462336 0x4C2E69: ??? (in /usr/bin/python2.7)
                    n1: 8462336 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                     n1: 8462336 0x4EA394: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
                      n1: 8462336 0x49A4EB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
                       n1: 8462336 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
                        n1: 8462336 0x4A7F16: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
                         n1: 8462336 0x53CDDF: ??? (in /usr/bin/python2.7)
                          n1: 8462336 0x4A4189: ??? (in /usr/bin/python2.7)
                           n1: 8462336 0x53D7D9: ??? (in /usr/bin/python2.7)
                            n1: 8462336 0x4FC1A1: ??? (in /usr/bin/python2.7)
                             n1: 8462336 0x53E0A2: ??? (in /usr/bin/python2.7)
                              n0: 8462336 0x4C2E69: ??? (in /usr/bin/python2.7)
          n1: 4354048 0x5EB0700: do_dlopen (dl-libc.c:89)
           n1: 4354048 0x400F174: _dl_catch_error (dl-error.c:178)
            n1: 4354048 0x5EB07C2: __libc_dlopen_mode (dl-libc.c:48)
             n1: 4354048 0x5E85B1C: nss_load_library.isra.1 (nsswitch.c:372)
              n2: 4354048 0x5E8657B: __nss_lookup_function (nsswitch.c:474)
               n1: 2203648 0x5E8678A: __nss_lookup (nsswitch.c:202)
                n1: 2203648 0x5E3EE16: getpwuid_r@@GLIBC_2.2.5 (getXXbyYY_r.c:203)
                 n1: 2203648 0x5E3E5F1: getpwuid (getXXbyYY.c:117)
                  n1: 2203648 0x66EFD6F: sandbox_check (in /usr/lib/libsandbox.so.0.3.5)
                   n1: 2203648 0x64E2D1E: Sandbox_new (in /usr/local/lib/python2.7/dist-packages/sandbox/_sandbox.so)
                    n1: 2203648 0x4DB5E6: ??? (in /usr/bin/python2.7)
                     n1: 2203648 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                      n1: 2203648 0x498468: PyEval_EvalFrameEx (in /usr/bin/python2.7)
                       n1: 2203648 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
                        n1: 2203648 0x4A907F: PyRun_FileExFlags (in /usr/bin/python2.7)
                         n1: 2203648 0x4A930F: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
                          n1: 2203648 0x4AA8BB: Py_Main (in /usr/bin/python2.7)
                           n0: 2203648 0x5DA176B: (below main) (libc-start.c:226)
               n1: 2150400 0x770063D: ???
                n1: 2150400 0x5E3ECFB: getpwuid_r@@GLIBC_2.2.5 (getXXbyYY_r.c:256)
                 n1: 2150400 0x5E3E5F1: getpwuid (getXXbyYY.c:117)
                  n1: 2150400 0x66EFD6F: sandbox_check (in /usr/lib/libsandbox.so.0.3.5)
                   n1: 2150400 0x64E2D1E: Sandbox_new (in /usr/local/lib/python2.7/dist-packages/sandbox/_sandbox.so)
                    n1: 2150400 0x4DB5E6: ??? (in /usr/bin/python2.7)
                     n1: 2150400 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                      n1: 2150400 0x498468: PyEval_EvalFrameEx (in /usr/bin/python2.7)
                       n1: 2150400 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
                        n1: 2150400 0x4A907F: PyRun_FileExFlags (in /usr/bin/python2.7)
                         n1: 2150400 0x4A930F: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
                          n1: 2150400 0x4AA8BB: Py_Main (in /usr/bin/python2.7)
                           n0: 2150400 0x5DA176B: (below main) (libc-start.c:226)
    n1: 6422528 0x4013849: dl_open_worker (dl-open.c:225)
     n1: 6422528 0x400F174: _dl_catch_error (dl-error.c:178)
      n2: 6422528 0x4013318: _dl_open (dl-open.c:639)
       n1: 4280320 0x5EB0700: do_dlopen (dl-libc.c:89)
        n1: 4280320 0x400F174: _dl_catch_error (dl-error.c:178)
         n1: 4280320 0x5EB07C2: __libc_dlopen_mode (dl-libc.c:48)
          n1: 4280320 0x5E85B1C: nss_load_library.isra.1 (nsswitch.c:372)
           n2: 4280320 0x5E8657B: __nss_lookup_function (nsswitch.c:474)
            n1: 2146304 0x770063D: ???
             n1: 2146304 0x5E3ECFB: getpwuid_r@@GLIBC_2.2.5 (getXXbyYY_r.c:256)
              n1: 2146304 0x5E3E5F1: getpwuid (getXXbyYY.c:117)
               n1: 2146304 0x66EFD6F: sandbox_check (in /usr/lib/libsandbox.so.0.3.5)
                n1: 2146304 0x64E2D1E: Sandbox_new (in /usr/local/lib/python2.7/dist-packages/sandbox/_sandbox.so)
                 n1: 2146304 0x4DB5E6: ??? (in /usr/bin/python2.7)
                  n1: 2146304 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                   n1: 2146304 0x498468: PyEval_EvalFrameEx (in /usr/bin/python2.7)
                    n1: 2146304 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
                     n1: 2146304 0x4A907F: PyRun_FileExFlags (in /usr/bin/python2.7)
                      n1: 2146304 0x4A930F: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
                       n1: 2146304 0x4AA8BB: Py_Main (in /usr/bin/python2.7)
                        n0: 2146304 0x5DA176B: (below main) (libc-start.c:226)
            n1: 2134016 0x5E8678A: __nss_lookup (nsswitch.c:202)
             n1: 2134016 0x5E3EE16: getpwuid_r@@GLIBC_2.2.5 (getXXbyYY_r.c:203)
              n1: 2134016 0x5E3E5F1: getpwuid (getXXbyYY.c:117)
               n1: 2134016 0x66EFD6F: sandbox_check (in /usr/lib/libsandbox.so.0.3.5)
                n1: 2134016 0x64E2D1E: Sandbox_new (in /usr/local/lib/python2.7/dist-packages/sandbox/_sandbox.so)
                 n1: 2134016 0x4DB5E6: ??? (in /usr/bin/python2.7)
                  n1: 2134016 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                   n1: 2134016 0x498468: PyEval_EvalFrameEx (in /usr/bin/python2.7)
                    n1: 2134016 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
                     n1: 2134016 0x4A907F: PyRun_FileExFlags (in /usr/bin/python2.7)
                      n1: 2134016 0x4A930F: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
                       n1: 2134016 0x4AA8BB: Py_Main (in /usr/bin/python2.7)
                        n0: 2134016 0x5DA176B: (below main) (libc-start.c:226)
       n1: 2142208 0x4E44F24: dlopen_doit (dlopen.c:67)
        n1: 2142208 0x400F174: _dl_catch_error (dl-error.c:178)
         n1: 2142208 0x4E4552D: _dlerror_run (dlerror.c:164)
          n1: 2142208 0x4E44FBF: dlopen@@GLIBC_2.2.5 (dlopen.c:88)
           n1: 2142208 0x561838: _PyImport_GetDynLoadFunc (in /usr/bin/python2.7)
            n1: 2142208 0x47AF17: _PyImport_LoadDynamicModule (in /usr/bin/python2.7)
             n1: 2142208 0x53D7D9: ??? (in /usr/bin/python2.7)
              n1: 2142208 0x53DCA8: ??? (in /usr/bin/python2.7)
               n1: 2142208 0x53E1B1: ??? (in /usr/bin/python2.7)
                n1: 2142208 0x4C2E69: ??? (in /usr/bin/python2.7)
                 n1: 2142208 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                  n1: 2142208 0x4EA394: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
                   n1: 2142208 0x49A4EB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
                    n1: 2142208 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
                     n1: 2142208 0x4A7F16: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
                      n1: 2142208 0x53CDDF: ??? (in /usr/bin/python2.7)
                       n1: 2142208 0x4A4189: ??? (in /usr/bin/python2.7)
                        n1: 2142208 0x53D7D9: ??? (in /usr/bin/python2.7)
                         n1: 2142208 0x4FC1A1: ??? (in /usr/bin/python2.7)
                          n1: 2142208 0x53E0A2: ??? (in /usr/bin/python2.7)
                           n1: 2142208 0x4C2E69: ??? (in /usr/bin/python2.7)
                            n1: 2142208 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                             n1: 2142208 0x4EA394: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
                              n0: 2142208 0x49A4EB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
    n1: 2105344 0x400188C: map_doit (rtld.c:633)
     n1: 2105344 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 2105344 0x4000ECD: do_preload (rtld.c:822)
       n1: 2105344 0x4004118: dl_main (rtld.c:1717)
        n1: 2105344 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 2105344 0x4005363: _dl_start (rtld.c:338)
          n1: 2105344 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 2105344 0x2: ???
            n1: 2105344 0x7FF0007A5: ???
             n1: 2105344 0x7FF0007AC: ???
              n1: 2105344 0x7FF0007BB: ???
               n0: 2105344 0x7FF0007BD: ???
  n1: 4259840 0x4007148: _dl_map_object_from_fd (dl-load.c:1392)
   n1: 4259840 0x4008698: _dl_map_object (dl-load.c:2568)
    n1: 4259840 0x400CFE0: openaux (dl-deps.c:65)
     n1: 4259840 0x400F174: _dl_catch_error (dl-error.c:178)
      n2: 4259840 0x400D6BC: _dl_map_object_deps (dl-deps.c:258)
       n1: 4202496 0x40138A7: dl_open_worker (dl-open.c:262)
        n1: 4202496 0x400F174: _dl_catch_error (dl-error.c:178)
         n2: 4202496 0x4013318: _dl_open (dl-open.c:639)
          n1: 4194304 0x4E44F24: dlopen_doit (dlopen.c:67)
           n1: 4194304 0x400F174: _dl_catch_error (dl-error.c:178)
            n1: 4194304 0x4E4552D: _dlerror_run (dlerror.c:164)
             n1: 4194304 0x4E44FBF: dlopen@@GLIBC_2.2.5 (dlopen.c:88)
              n1: 4194304 0x561838: _PyImport_GetDynLoadFunc (in /usr/bin/python2.7)
               n1: 4194304 0x47AF17: _PyImport_LoadDynamicModule (in /usr/bin/python2.7)
                n1: 4194304 0x53D7D9: ??? (in /usr/bin/python2.7)
                 n1: 4194304 0x53DCA8: ??? (in /usr/bin/python2.7)
                  n1: 4194304 0x53E1B1: ??? (in /usr/bin/python2.7)
                   n1: 4194304 0x4C2E69: ??? (in /usr/bin/python2.7)
                    n1: 4194304 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                     n1: 4194304 0x4EA394: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
                      n1: 4194304 0x49A4EB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
                       n1: 4194304 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
                        n1: 4194304 0x4A7F16: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
                         n1: 4194304 0x53CDDF: ??? (in /usr/bin/python2.7)
                          n1: 4194304 0x4A4189: ??? (in /usr/bin/python2.7)
                           n1: 4194304 0x53D7D9: ??? (in /usr/bin/python2.7)
                            n1: 4194304 0x4FC1A1: ??? (in /usr/bin/python2.7)
                             n1: 4194304 0x53E0A2: ??? (in /usr/bin/python2.7)
                              n0: 4194304 0x4C2E69: ??? (in /usr/bin/python2.7)
          n0: 8192 in 1 place, below massif's threshold (01.00%)
       n0: 57344 in 1 place, below massif's threshold (01.00%)
  n0: 368640 in 3 places, all below massif's threshold (01.00%)
 n4: 11603968 0x5E70169: mmap (syscall-template.S:82)
  n1: 8392704 0x4C2FA2C: pthread_create@@GLIBC_2.2.5 (allocatestack.c:495)
   n1: 8392704 0x400F304: call_init.part.0 (dl-init.c:85)
    n1: 8392704 0x400F3DD: _dl_init (dl-init.c:52)
     n1: 8392704 0x4013AD8: dl_open_worker (dl-open.c:549)
      n1: 8392704 0x400F174: _dl_catch_error (dl-error.c:178)
       n1: 8392704 0x4013318: _dl_open (dl-open.c:639)
        n1: 8392704 0x4E44F24: dlopen_doit (dlopen.c:67)
         n1: 8392704 0x400F174: _dl_catch_error (dl-error.c:178)
          n1: 8392704 0x4E4552D: _dlerror_run (dlerror.c:164)
           n1: 8392704 0x4E44FBF: dlopen@@GLIBC_2.2.5 (dlopen.c:88)
            n1: 8392704 0x561838: _PyImport_GetDynLoadFunc (in /usr/bin/python2.7)
             n1: 8392704 0x47AF17: _PyImport_LoadDynamicModule (in /usr/bin/python2.7)
              n1: 8392704 0x53D7D9: ??? (in /usr/bin/python2.7)
               n1: 8392704 0x53DCA8: ??? (in /usr/bin/python2.7)
                n1: 8392704 0x53E1B1: ??? (in /usr/bin/python2.7)
                 n1: 8392704 0x4C2E69: ??? (in /usr/bin/python2.7)
                  n1: 8392704 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                   n1: 8392704 0x4EA394: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
                    n1: 8392704 0x49A4EB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
                     n1: 8392704 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
                      n1: 8392704 0x4A7F16: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
                       n1: 8392704 0x53CDDF: ??? (in /usr/bin/python2.7)
                        n1: 8392704 0x4A4189: ??? (in /usr/bin/python2.7)
                         n1: 8392704 0x53D7D9: ??? (in /usr/bin/python2.7)
                          n1: 8392704 0x4FC1A1: ??? (in /usr/bin/python2.7)
                           n1: 8392704 0x53E0A2: ??? (in /usr/bin/python2.7)
                            n1: 8392704 0x4C2E69: ??? (in /usr/bin/python2.7)
                             n1: 8392704 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                              n0: 8392704 0x4EA394: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
  n1: 1609728 0x5DADDC4: _nl_load_locale_from_archive (loadarchive.c:228)
   n1: 1609728 0x5DACE11: _nl_find_locale (findlocale.c:107)
    n1: 1609728 0x5DAC4F8: setlocale (setlocale.c:379)
     n1: 1609728 0x52D353: ??? (in /usr/bin/python2.7)
      n1: 1609728 0x4AA66B: Py_Main (in /usr/bin/python2.7)
       n0: 1609728 0x5DA176B: (below main) (libc-start.c:226)
  n1: 1601536 0x5E015CB: _int_malloc (malloc.c:2400)
   n2: 1601536 0x5E030B3: malloc (malloc.c:2924)
    n2: 1064960 0x423FC6: PyObject_Malloc (in /usr/bin/python2.7)
     n1: 798720 0x54390B: _PyObject_GC_Malloc (in /usr/bin/python2.7)
      n1: 798720 0x4DFB30: PyTuple_New (in /usr/bin/python2.7)
       n0: 798720 in 3 places, all below massif's threshold (01.00%)
     n0: 266240 in 1 place, below massif's threshold (01.00%)
    n0: 536576 in 2 places, all below massif's threshold (01.00%)
  n0: 0 in 1 place, below massif's threshold (01.00%)
 n0: 3239936 0xFFFFFFFFFFFFFFFF: ???
 n1: 1007616 0x5E6C4D9: brk (brk.c:32)
  n1: 1007616 0x5E6C583: sbrk (sbrk.c:54)
   n1: 1007616 0x5E057D7: __default_morecore (morecore.c:49)
    n1: 1007616 0x5E01178: _int_malloc (malloc.c:2535)
     n2: 1007616 0x5E030B3: malloc (malloc.c:2924)
      n1: 737280 0x4F8EBD: ??? (in /usr/bin/python2.7)
       n0: 737280 in 5 places, all below massif's threshold (01.00%)
      n0: 270336 in 2 places, all below massif's threshold (01.00%)
#-----------
snapshot=85
#-----------
time=46289773
mem_heap_B=66129920
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=86
#-----------
time=46321258
mem_heap_B=66125824
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=87
#-----------
time=46367171
mem_heap_B=66125824
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=88
#-----------
time=46400905
mem_heap_B=66125824
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=89
#-----------
time=46433668
mem_heap_B=66125824
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=90
#-----------
time=46458229
mem_heap_B=66125824
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=91
#-----------
time=46490805
mem_heap_B=66125824
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=92
#-----------
time=48647137
mem_heap_B=217128960
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=93
#-----------
time=48647152
mem_heap_B=165990400
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=peak
n4: 165990400 (page allocation syscalls) mmap/mremap/brk, --alloc-fns, etc.
 n3: 111468544 0x5E70169: mmap (syscall-template.S:82)
  n1: 83079168 0x5DFE377: new_heap (arena.c:554)
   n1: 83079168 0x5DFF2B3: arena_get2.isra.5.part.6 (arena.c:712)
    n1: 83079168 0x5E031E7: malloc (arena.c:824)
     n1: 83079168 0x4D3286: ??? (in /usr/bin/python2.7)
      n1: 83079168 0x4D348A: PyGILState_Ensure (in /usr/bin/python2.7)
       n1: 83079168 0x64E2DB9: SandboxPolicy_entry (in /usr/local/lib/python2.7/dist-packages/sandbox/_sandbox.so)
        n1: 83079168 0x66EDE5E: sandbox_watcher (in /usr/lib/libsandbox.so.0.3.5)
         n0: 83079168 0x4C2EE98: start_thread (pthread_create.c:308)
  n3: 25178112 0x4C2FA2C: pthread_create@@GLIBC_2.2.5 (allocatestack.c:495)
   n1: 8392704 0x400F304: call_init.part.0 (dl-init.c:85)
    n1: 8392704 0x400F3DD: _dl_init (dl-init.c:52)
     n1: 8392704 0x4013AD8: dl_open_worker (dl-open.c:549)
      n1: 8392704 0x400F174: _dl_catch_error (dl-error.c:178)
       n1: 8392704 0x4013318: _dl_open (dl-open.c:639)
        n1: 8392704 0x4E44F24: dlopen_doit (dlopen.c:67)
         n1: 8392704 0x400F174: _dl_catch_error (dl-error.c:178)
          n1: 8392704 0x4E4552D: _dlerror_run (dlerror.c:164)
           n1: 8392704 0x4E44FBF: dlopen@@GLIBC_2.2.5 (dlopen.c:88)
            n1: 8392704 0x561838: _PyImport_GetDynLoadFunc (in /usr/bin/python2.7)
             n1: 8392704 0x47AF17: _PyImport_LoadDynamicModule (in /usr/bin/python2.7)
              n1: 8392704 0x53D7D9: ??? (in /usr/bin/python2.7)
               n1: 8392704 0x53DCA8: ??? (in /usr/bin/python2.7)
                n1: 8392704 0x53E1B1: ??? (in /usr/bin/python2.7)
                 n1: 8392704 0x4C2E69: ??? (in /usr/bin/python2.7)
                  n1: 8392704 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                   n1: 8392704 0x4EA394: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
                    n1: 8392704 0x49A4EB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
                     n1: 8392704 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
                      n1: 8392704 0x4A7F16: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
                       n1: 8392704 0x53CDDF: ??? (in /usr/bin/python2.7)
                        n1: 8392704 0x4A4189: ??? (in /usr/bin/python2.7)
                         n1: 8392704 0x53D7D9: ??? (in /usr/bin/python2.7)
                          n1: 8392704 0x4FC1A1: ??? (in /usr/bin/python2.7)
                           n1: 8392704 0x53E0A2: ??? (in /usr/bin/python2.7)
                            n1: 8392704 0x4C2E69: ??? (in /usr/bin/python2.7)
                             n1: 8392704 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                              n0: 8392704 0x4EA394: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
   n1: 8392704 0x66F02FD: sandbox_execute (in /usr/lib/libsandbox.so.0.3.5)
    n1: 8392704 0x64E1D7C: Sandbox_run (in /usr/local/lib/python2.7/dist-packages/sandbox/_sandbox.so)
     n1: 8392704 0x498908: PyEval_EvalFrameEx (in /usr/bin/python2.7)
      n1: 8392704 0x498600: PyEval_EvalFrameEx (in /usr/bin/python2.7)
       n1: 8392704 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
        n1: 8392704 0x4A907F: PyRun_FileExFlags (in /usr/bin/python2.7)
         n1: 8392704 0x4A930F: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
          n1: 8392704 0x4AA8BB: Py_Main (in /usr/bin/python2.7)
           n0: 8392704 0x5DA176B: (below main) (libc-start.c:226)
   n1: 8392704 0x66F0322: sandbox_execute (in /usr/lib/libsandbox.so.0.3.5)
    n1: 8392704 0x64E1D7C: Sandbox_run (in /usr/local/lib/python2.7/dist-packages/sandbox/_sandbox.so)
     n1: 8392704 0x498908: PyEval_EvalFrameEx (in /usr/bin/python2.7)
      n1: 8392704 0x498600: PyEval_EvalFrameEx (in /usr/bin/python2.7)
       n1: 8392704 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
        n1: 8392704 0x4A907F: PyRun_FileExFlags (in /usr/bin/python2.7)
         n1: 8392704 0x4A930F: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
          n1: 8392704 0x4AA8BB: Py_Main (in /usr/bin/python2.7)
           n0: 8392704 0x5DA176B: (below main) (libc-start.c:226)
  n0: 3211264 in 4 places, all below massif's threshold (01.00%)
 n3: 50274304 0x4018429: mmap (syscall-template.S:82)
  n1: 45649920 0x4006B67: _dl_map_object_from_fd (dl-load.c:1283)
   n3: 45649920 0x4008698: _dl_map_object (dl-load.c:2568)
    n1: 37122048 0x400CFE0: openaux (dl-deps.c:65)
     n1: 37122048 0x400F174: _dl_catch_error (dl-error.c:178)
      n2: 37122048 0x400D6BC: _dl_map_object_deps (dl-deps.c:258)
       n1: 24305664 0x400350B: dl_main (rtld.c:1826)
        n1: 24305664 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 24305664 0x4005363: _dl_start (rtld.c:338)
          n1: 24305664 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 24305664 0x2: ???
            n1: 24305664 0x7FF0007A5: ???
             n1: 24305664 0x7FF0007AC: ???
              n1: 24305664 0x7FF0007BB: ???
               n0: 24305664 0x7FF0007BD: ???
       n1: 12816384 0x40138A7: dl_open_worker (dl-open.c:262)
        n1: 12816384 0x400F174: _dl_catch_error (dl-error.c:178)
         n2: 12816384 0x4013318: _dl_open (dl-open.c:639)
          n1: 8462336 0x4E44F24: dlopen_doit (dlopen.c:67)
           n1: 8462336 0x400F174: _dl_catch_error (dl-error.c:178)
            n1: 8462336 0x4E4552D: _dlerror_run (dlerror.c:164)
             n1: 8462336 0x4E44FBF: dlopen@@GLIBC_2.2.5 (dlopen.c:88)
              n1: 8462336 0x561838: _PyImport_GetDynLoadFunc (in /usr/bin/python2.7)
               n1: 8462336 0x47AF17: _PyImport_LoadDynamicModule (in /usr/bin/python2.7)
                n1: 8462336 0x53D7D9: ??? (in /usr/bin/python2.7)
                 n1: 8462336 0x53DCA8: ??? (in /usr/bin/python2.7)
                  n1: 8462336 0x53E1B1: ??? (in /usr/bin/python2.7)
                   n1: 8462336 0x4C2E69: ??? (in /usr/bin/python2.7)
                    n1: 8462336 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                     n1: 8462336 0x4EA394: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
                      n1: 8462336 0x49A4EB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
                       n1: 8462336 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
                        n1: 8462336 0x4A7F16: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
                         n1: 8462336 0x53CDDF: ??? (in /usr/bin/python2.7)
                          n1: 8462336 0x4A4189: ??? (in /usr/bin/python2.7)
                           n1: 8462336 0x53D7D9: ??? (in /usr/bin/python2.7)
                            n1: 8462336 0x4FC1A1: ??? (in /usr/bin/python2.7)
                             n1: 8462336 0x53E0A2: ??? (in /usr/bin/python2.7)
                              n0: 8462336 0x4C2E69: ??? (in /usr/bin/python2.7)
          n1: 4354048 0x5EB0700: do_dlopen (dl-libc.c:89)
           n1: 4354048 0x400F174: _dl_catch_error (dl-error.c:178)
            n1: 4354048 0x5EB07C2: __libc_dlopen_mode (dl-libc.c:48)
             n1: 4354048 0x5E85B1C: nss_load_library.isra.1 (nsswitch.c:372)
              n2: 4354048 0x5E8657B: __nss_lookup_function (nsswitch.c:474)
               n1: 2203648 0x5E8678A: __nss_lookup (nsswitch.c:202)
                n1: 2203648 0x5E3EE16: getpwuid_r@@GLIBC_2.2.5 (getXXbyYY_r.c:203)
                 n1: 2203648 0x5E3E5F1: getpwuid (getXXbyYY.c:117)
                  n1: 2203648 0x66EFD6F: sandbox_check (in /usr/lib/libsandbox.so.0.3.5)
                   n1: 2203648 0x64E2D1E: Sandbox_new (in /usr/local/lib/python2.7/dist-packages/sandbox/_sandbox.so)
                    n1: 2203648 0x4DB5E6: ??? (in /usr/bin/python2.7)
                     n1: 2203648 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                      n1: 2203648 0x498468: PyEval_EvalFrameEx (in /usr/bin/python2.7)
                       n1: 2203648 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
                        n1: 2203648 0x4A907F: PyRun_FileExFlags (in /usr/bin/python2.7)
                         n1: 2203648 0x4A930F: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
                          n1: 2203648 0x4AA8BB: Py_Main (in /usr/bin/python2.7)
                           n0: 2203648 0x5DA176B: (below main) (libc-start.c:226)
               n1: 2150400 0x770063D: ???
                n1: 2150400 0x5E3ECFB: getpwuid_r@@GLIBC_2.2.5 (getXXbyYY_r.c:256)
                 n1: 2150400 0x5E3E5F1: getpwuid (getXXbyYY.c:117)
                  n1: 2150400 0x66EFD6F: sandbox_check (in /usr/lib/libsandbox.so.0.3.5)
                   n1: 2150400 0x64E2D1E: Sandbox_new (in /usr/local/lib/python2.7/dist-packages/sandbox/_sandbox.so)
                    n1: 2150400 0x4DB5E6: ??? (in /usr/bin/python2.7)
                     n1: 2150400 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                      n1: 2150400 0x498468: PyEval_EvalFrameEx (in /usr/bin/python2.7)
                       n1: 2150400 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
                        n1: 2150400 0x4A907F: PyRun_FileExFlags (in /usr/bin/python2.7)
                         n1: 2150400 0x4A930F: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
                          n1: 2150400 0x4AA8BB: Py_Main (in /usr/bin/python2.7)
                           n0: 2150400 0x5DA176B: (below main) (libc-start.c:226)
    n1: 6422528 0x4013849: dl_open_worker (dl-open.c:225)
     n1: 6422528 0x400F174: _dl_catch_error (dl-error.c:178)
      n2: 6422528 0x4013318: _dl_open (dl-open.c:639)
       n1: 4280320 0x5EB0700: do_dlopen (dl-libc.c:89)
        n1: 4280320 0x400F174: _dl_catch_error (dl-error.c:178)
         n1: 4280320 0x5EB07C2: __libc_dlopen_mode (dl-libc.c:48)
          n1: 4280320 0x5E85B1C: nss_load_library.isra.1 (nsswitch.c:372)
           n2: 4280320 0x5E8657B: __nss_lookup_function (nsswitch.c:474)
            n1: 2146304 0x770063D: ???
             n1: 2146304 0x5E3ECFB: getpwuid_r@@GLIBC_2.2.5 (getXXbyYY_r.c:256)
              n1: 2146304 0x5E3E5F1: getpwuid (getXXbyYY.c:117)
               n1: 2146304 0x66EFD6F: sandbox_check (in /usr/lib/libsandbox.so.0.3.5)
                n1: 2146304 0x64E2D1E: Sandbox_new (in /usr/local/lib/python2.7/dist-packages/sandbox/_sandbox.so)
                 n1: 2146304 0x4DB5E6: ??? (in /usr/bin/python2.7)
                  n1: 2146304 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                   n1: 2146304 0x498468: PyEval_EvalFrameEx (in /usr/bin/python2.7)
                    n1: 2146304 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
                     n1: 2146304 0x4A907F: PyRun_FileExFlags (in /usr/bin/python2.7)
                      n1: 2146304 0x4A930F: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
                       n1: 2146304 0x4AA8BB: Py_Main (in /usr/bin/python2.7)
                        n0: 2146304 0x5DA176B: (below main) (libc-start.c:226)
            n1: 2134016 0x5E8678A: __nss_lookup (nsswitch.c:202)
             n1: 2134016 0x5E3EE16: getpwuid_r@@GLIBC_2.2.5 (getXXbyYY_r.c:203)
              n1: 2134016 0x5E3E5F1: getpwuid (getXXbyYY.c:117)
               n1: 2134016 0x66EFD6F: sandbox_check (in /usr/lib/libsandbox.so.0.3.5)
                n1: 2134016 0x64E2D1E: Sandbox_new (in /usr/local/lib/python2.7/dist-packages/sandbox/_sandbox.so)
                 n1: 2134016 0x4DB5E6: ??? (in /usr/bin/python2.7)
                  n1: 2134016 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                   n1: 2134016 0x498468: PyEval_EvalFrameEx (in /usr/bin/python2.7)
                    n1: 2134016 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
                     n1: 2134016 0x4A907F: PyRun_FileExFlags (in /usr/bin/python2.7)
                      n1: 2134016 0x4A930F: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
                       n1: 2134016 0x4AA8BB: Py_Main (in /usr/bin/python2.7)
                        n0: 2134016 0x5DA176B: (below main) (libc-start.c:226)
       n1: 2142208 0x4E44F24: dlopen_doit (dlopen.c:67)
        n1: 2142208 0x400F174: _dl_catch_error (dl-error.c:178)
         n1: 2142208 0x4E4552D: _dlerror_run (dlerror.c:164)
          n1: 2142208 0x4E44FBF: dlopen@@GLIBC_2.2.5 (dlopen.c:88)
           n1: 2142208 0x561838: _PyImport_GetDynLoadFunc (in /usr/bin/python2.7)
            n1: 2142208 0x47AF17: _PyImport_LoadDynamicModule (in /usr/bin/python2.7)
             n1: 2142208 0x53D7D9: ??? (in /usr/bin/python2.7)
              n1: 2142208 0x53DCA8: ??? (in /usr/bin/python2.7)
               n1: 2142208 0x53E1B1: ??? (in /usr/bin/python2.7)
                n1: 2142208 0x4C2E69: ??? (in /usr/bin/python2.7)
                 n1: 2142208 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                  n1: 2142208 0x4EA394: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
                   n1: 2142208 0x49A4EB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
                    n1: 2142208 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
                     n1: 2142208 0x4A7F16: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
                      n1: 2142208 0x53CDDF: ??? (in /usr/bin/python2.7)
                       n1: 2142208 0x4A4189: ??? (in /usr/bin/python2.7)
                        n1: 2142208 0x53D7D9: ??? (in /usr/bin/python2.7)
                         n1: 2142208 0x4FC1A1: ??? (in /usr/bin/python2.7)
                          n1: 2142208 0x53E0A2: ??? (in /usr/bin/python2.7)
                           n1: 2142208 0x4C2E69: ??? (in /usr/bin/python2.7)
                            n1: 2142208 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                             n1: 2142208 0x4EA394: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
                              n0: 2142208 0x49A4EB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
    n1: 2105344 0x400188C: map_doit (rtld.c:633)
     n1: 2105344 0x400F174: _dl_catch_error (dl-error.c:178)
      n1: 2105344 0x4000ECD: do_preload (rtld.c:822)
       n1: 2105344 0x4004118: dl_main (rtld.c:1717)
        n1: 2105344 0x4015B22: _dl_sysdep_start (dl-sysdep.c:244)
         n1: 2105344 0x4005363: _dl_start (rtld.c:338)
          n1: 2105344 0x40016B6: ??? (in /lib/x86_64-linux-gnu/ld-2.15.so)
           n1: 2105344 0x2: ???
            n1: 2105344 0x7FF0007A5: ???
             n1: 2105344 0x7FF0007AC: ???
              n1: 2105344 0x7FF0007BB: ???
               n0: 2105344 0x7FF0007BD: ???
  n1: 4259840 0x4007148: _dl_map_object_from_fd (dl-load.c:1392)
   n1: 4259840 0x4008698: _dl_map_object (dl-load.c:2568)
    n1: 4259840 0x400CFE0: openaux (dl-deps.c:65)
     n1: 4259840 0x400F174: _dl_catch_error (dl-error.c:178)
      n2: 4259840 0x400D6BC: _dl_map_object_deps (dl-deps.c:258)
       n1: 4202496 0x40138A7: dl_open_worker (dl-open.c:262)
        n1: 4202496 0x400F174: _dl_catch_error (dl-error.c:178)
         n2: 4202496 0x4013318: _dl_open (dl-open.c:639)
          n1: 4194304 0x4E44F24: dlopen_doit (dlopen.c:67)
           n1: 4194304 0x400F174: _dl_catch_error (dl-error.c:178)
            n1: 4194304 0x4E4552D: _dlerror_run (dlerror.c:164)
             n1: 4194304 0x4E44FBF: dlopen@@GLIBC_2.2.5 (dlopen.c:88)
              n1: 4194304 0x561838: _PyImport_GetDynLoadFunc (in /usr/bin/python2.7)
               n1: 4194304 0x47AF17: _PyImport_LoadDynamicModule (in /usr/bin/python2.7)
                n1: 4194304 0x53D7D9: ??? (in /usr/bin/python2.7)
                 n1: 4194304 0x53DCA8: ??? (in /usr/bin/python2.7)
                  n1: 4194304 0x53E1B1: ??? (in /usr/bin/python2.7)
                   n1: 4194304 0x4C2E69: ??? (in /usr/bin/python2.7)
                    n1: 4194304 0x4E9F34: PyObject_Call (in /usr/bin/python2.7)
                     n1: 4194304 0x4EA394: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
                      n1: 4194304 0x49A4EB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
                       n1: 4194304 0x49F1BE: PyEval_EvalCodeEx (in /usr/bin/python2.7)
                        n1: 4194304 0x4A7F16: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
                         n1: 4194304 0x53CDDF: ??? (in /usr/bin/python2.7)
                          n1: 4194304 0x4A4189: ??? (in /usr/bin/python2.7)
                           n1: 4194304 0x53D7D9: ??? (in /usr/bin/python2.7)
                            n1: 4194304 0x4FC1A1: ??? (in /usr/bin/python2.7)
                             n1: 4194304 0x53E0A2: ??? (in /usr/bin/python2.7)
                              n0: 4194304 0x4C2E69: ??? (in /usr/bin/python2.7)
          n0: 8192 in 1 place, below massif's threshold (01.00%)
       n0: 57344 in 1 place, below massif's threshold (01.00%)
  n0: 364544 in 3 places, all below massif's threshold (01.00%)
 n0: 3239936 0xFFFFFFFFFFFFFFFF: ???
 n0: 1007616 in 1 place, below massif's threshold (01.00%)
#-----------
snapshot=94
#-----------
time=48693253
mem_heap_B=150024192
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=95
#-----------
time=50044296
mem_heap_B=149688320
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=96
#-----------
time=51539634
mem_heap_B=148078592
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=97
#-----------
time=51555221
mem_heap_B=118616064
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
